// =============================================================================
// Tests - WolverineOpenApiOperationTransformer
// =============================================================================
// Vérifie la normalisation des métadonnées OpenAPI auto-générées par Wolverine :
//   - operationId remplacé par le nom de l'endpoint
//   - description auto-générée supprimée
//   - réponse 200 fantôme avec IResult supprimée
// =============================================================================

using Granit.Http.ApiDocumentation.Transformers;
using Microsoft.AspNetCore.Http.Metadata;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Abstractions;
using Microsoft.AspNetCore.Mvc.ApiExplorer;
using Microsoft.AspNetCore.OpenApi;
using Microsoft.AspNetCore.Routing;
using Microsoft.OpenApi;
using NSubstitute;
using Shouldly;
using Xunit;

namespace Granit.Http.ApiDocumentation.Tests;

public sealed class WolverineOpenApiOperationTransformerTests
{
    // --- operationId ---

    [Fact]
    public async Task TransformAsync_WithEndpointName_OverridesOperationId()
    {
        // Arrange
        WolverineOpenApiOperationTransformer transformer = new();
        OpenApiOperation operation = new() { OperationId = "POST_api_v1_gdpr_export" };
        OpenApiOperationTransformerContext context = BuildContext(new EndpointNameMetadata("RequestDataExport"));

        // Act
        await transformer.TransformAsync(operation, context, TestContext.Current.CancellationToken);

        // Assert
        operation.OperationId.ShouldBe("RequestDataExport");
    }

    [Fact]
    public async Task TransformAsync_WithWolverineAttributeName_OverridesOperationId()
    {
        // Arrange — simulates Wolverine's [WolverinePost(..., Name = "RequestDataExport")]
        WolverineOpenApiOperationTransformer transformer = new();
        OpenApiOperation operation = new() { OperationId = "POST_api_v1_gdpr_export" };
        Wolverine.Http.WolverinePostAttribute wolverineAttr = new() { Name = "RequestDataExport" };
        OpenApiOperationTransformerContext context = BuildContext(wolverineAttr);

        // Act
        await transformer.TransformAsync(operation, context, TestContext.Current.CancellationToken);

        // Assert
        operation.OperationId.ShouldBe("RequestDataExport");
    }

    [Fact]
    public async Task TransformAsync_WithoutEndpointName_PreservesOperationId()
    {
        // Arrange
        WolverineOpenApiOperationTransformer transformer = new();
        OpenApiOperation operation = new() { OperationId = "POST_api_v1_gdpr_export" };
        OpenApiOperationTransformerContext context = BuildContext();

        // Act
        await transformer.TransformAsync(operation, context, TestContext.Current.CancellationToken);

        // Assert
        operation.OperationId.ShouldBe("POST_api_v1_gdpr_export");
    }

    // --- description ---

    [Fact]
    public async Task TransformAsync_AutoGeneratedDescription_ClearedToNull()
    {
        // Arrange
        WolverineOpenApiOperationTransformer transformer = new();
        OpenApiOperation operation = new() { Description = "POST_api_v1_gdpr_export" };
        OpenApiOperationTransformerContext context = BuildContext();

        // Act
        await transformer.TransformAsync(operation, context, TestContext.Current.CancellationToken);

        // Assert
        operation.Description.ShouldBeNull();
    }

    [Theory]
    [InlineData("GET_api_v1_users_me")]
    [InlineData("DELETE_api_v1_gdpr_erasure")]
    [InlineData("PUT_api_v1_settings")]
    [InlineData("PATCH_api_v1_users")]
    public async Task TransformAsync_AutoGeneratedDescriptionVariants_AllCleared(string description)
    {
        // Arrange
        WolverineOpenApiOperationTransformer transformer = new();
        OpenApiOperation operation = new() { Description = description };
        OpenApiOperationTransformerContext context = BuildContext();

        // Act
        await transformer.TransformAsync(operation, context, TestContext.Current.CancellationToken);

        // Assert
        operation.Description.ShouldBeNull();
    }

    [Fact]
    public async Task TransformAsync_HumanDescription_Preserved()
    {
        // Arrange
        WolverineOpenApiOperationTransformer transformer = new();
        OpenApiOperation operation = new() { Description = "Returns the current user profile." };
        OpenApiOperationTransformerContext context = BuildContext();

        // Act
        await transformer.TransformAsync(operation, context, TestContext.Current.CancellationToken);

        // Assert
        operation.Description.ShouldBe("Returns the current user profile.");
    }

    // --- phantom 200 ---

    [Fact]
    public async Task TransformAsync_Phantom200WithExplicit202ViaInterface_Removes200()
    {
        // Arrange — IProducesResponseTypeMetadata (minimal API path)
        WolverineOpenApiOperationTransformer transformer = new();
        OpenApiOperation operation = new()
        {
            Responses = new OpenApiResponses
            {
                ["200"] = BuildIResultResponse(),
                ["202"] = new OpenApiResponse { Description = "Accepted" },
            },
        };

        IProducesResponseTypeMetadata produces202 = Substitute.For<IProducesResponseTypeMetadata>();
        produces202.StatusCode.Returns(202);

        OpenApiOperationTransformerContext context = BuildContext(produces202);

        // Act
        await transformer.TransformAsync(operation, context, TestContext.Current.CancellationToken);

        // Assert
        operation.Responses.ShouldNotContainKey("200");
        operation.Responses.ShouldContainKey("202");
    }

    [Fact]
    public async Task TransformAsync_Phantom200WithExplicit204ViaAttribute_Removes200()
    {
        // Arrange — ProducesResponseTypeAttribute (MVC path, used on Wolverine handlers)
        WolverineOpenApiOperationTransformer transformer = new();
        OpenApiOperation operation = new()
        {
            Responses = new OpenApiResponses
            {
                ["200"] = BuildIResultResponse(),
                ["204"] = new OpenApiResponse { Description = "No Content" },
            },
        };

        ProducesResponseTypeAttribute produces204 = new(204);

        OpenApiOperationTransformerContext context = BuildContext(produces204);

        // Act
        await transformer.TransformAsync(operation, context, TestContext.Current.CancellationToken);

        // Assert
        operation.Responses.ShouldNotContainKey("200");
        operation.Responses.ShouldContainKey("204");
    }

    [Fact]
    public async Task TransformAsync_Explicit200WithTypedSchema_Preserved()
    {
        // Arrange
        WolverineOpenApiOperationTransformer transformer = new();
        OpenApiResponse typedResponse = new()
        {
            Description = "OK",
            Content = new Dictionary<string, OpenApiMediaType>
            {
                ["application/json"] = new OpenApiMediaType
                {
                    Schema = new OpenApiSchemaReference("UserProfileResponse", null),
                },
            },
        };
        OpenApiOperation operation = new()
        {
            Responses = new OpenApiResponses { ["200"] = typedResponse },
        };

        IProducesResponseTypeMetadata produces200 = Substitute.For<IProducesResponseTypeMetadata>();
        produces200.StatusCode.Returns(200);

        OpenApiOperationTransformerContext context = BuildContext(produces200);

        // Act
        await transformer.TransformAsync(operation, context, TestContext.Current.CancellationToken);

        // Assert
        operation.Responses.ShouldContainKey("200");
    }

    [Fact]
    public async Task TransformAsync_NoResponses_NoException()
    {
        // Arrange
        WolverineOpenApiOperationTransformer transformer = new();
        OpenApiOperation operation = new();
        OpenApiOperationTransformerContext context = BuildContext();

        // Act
        Func<Task> act = () => transformer.TransformAsync(
            operation, context, TestContext.Current.CancellationToken);

        // Assert
        await Should.NotThrowAsync(act);
    }

    // --- Helpers ---

    private static OpenApiOperationTransformerContext BuildContext(params object[] metadata)
    {
        ActionDescriptor descriptor = new();
        descriptor.EndpointMetadata = [.. metadata];

        return new OpenApiOperationTransformerContext
        {
            DocumentName = "v1",
            Description = new ApiDescription
            {
                ActionDescriptor = descriptor,
                RelativePath = "api/test",
            },
            ApplicationServices = Substitute.For<IServiceProvider>(),
        };
    }

    private static OpenApiResponse BuildIResultResponse() =>
        new()
        {
            Description = "OK",
            Content = new Dictionary<string, OpenApiMediaType>
            {
                ["application/json"] = new OpenApiMediaType
                {
                    Schema = new OpenApiSchemaReference("IResult", null),
                },
            },
        };

}
