using Granit.Events;
using Granit.Metering;
using Granit.Metering.Domain;
using Granit.Metering.Events;
using Granit.MultiTenancy;
using Granit.Subscriptions.Events;

namespace Granit.Subscriptions.Handlers;

/// <summary>
/// Publishes <see cref="UsageSummaryReadyEto"/> for each active meter when a billing
/// cycle completes. Bridges subscription lifecycle events with metering aggregates so
/// that usage-based invoices can be generated by <see cref="UsageSummaryReadyHandler"/>.
/// </summary>
public class BillingCycleUsagePublisher
{
    public static async Task HandleAsync(
        BillingCycleCompletedEto eto,
        IMeterDefinitionReader meterReader,
        IUsageReader usageReader,
        IDistributedEventBus eventBus,
        ICurrentTenant currentTenant,
        CancellationToken cancellationToken)
    {
        using (currentTenant.Change(eto.TenantId))
        {
            IReadOnlyList<MeterDefinition> meters = await meterReader
                .GetActiveAsync(cancellationToken).ConfigureAwait(false);

            foreach (MeterDefinition meter in meters)
            {
                UsageAggregate? aggregate = await usageReader
                    .GetForPeriodAsync(
                        eto.TenantId,
                        meter.Id,
                        eto.PeriodStart,
                        eto.PeriodEnd,
                        cancellationToken)
                    .ConfigureAwait(false);

                if (aggregate is null || aggregate.AggregatedValue == 0)
                {
                    continue;
                }

                await eventBus.PublishAsync(
                    new UsageSummaryReadyEto(
                        eto.TenantId,
                        meter.Id,
                        meter.Name,
                        meter.Unit,
                        aggregate.AggregatedValue,
                        aggregate.EventCount,
                        eto.PeriodStart,
                        eto.PeriodEnd),
                    cancellationToken).ConfigureAwait(false);
            }
        }
    }
}
