<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <PackageId>Granit.Caching.StackExchangeRedis</PackageId>
    <Description>Redis provider for Granit.Caching. Replaces IDistributedCache (MemoryDistributedCache) with RedisCache (StackExchange.Redis). Enables AES-256 encryption automatically when CachingOptions.EncryptValues = true.</Description>
    <IsPackable>true</IsPackable>
  </PropertyGroup>

  <ItemGroup>
    <InternalsVisibleTo Include="Granit.Caching.StackExchangeRedis.Tests" />
    <InternalsVisibleTo Include="Granit.Http.OutputCaching.StackExchangeRedis" />
    <InternalsVisibleTo Include="Granit.Http.OutputCaching.StackExchangeRedis.Tests" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.Extensions.Caching.StackExchangeRedis" />
    <PackageReference Include="StackExchange.Redis" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Granit.Caching\Granit.Caching.csproj" />
  </ItemGroup>

</Project>
