using Granit.DataExchange.Export;
using Granit.DataExchange.Export.Internal;
using Granit.DataExchange.Export.Pipeline;
using Microsoft.Extensions.DependencyInjection;
using Microsoft.Extensions.Options;
using Shouldly;
using Xunit;

namespace Granit.DataExchange.Tests.Export.Pipeline;

public sealed class ExportPipelineRegistryTests
{
    // ── Find ─────────────────────────────────────────────────────────────

    [Fact]
    public void Find_existing_name_returns_descriptor()
    {
        ExportPipelineRegistry registry = CreateRegistry(
            bindings: [new ExportEntityBinding<Person>(new PersonExportDefinition())]);

        IExportPipelineDescriptor? descriptor = registry.Find("Test.People");

        descriptor.ShouldNotBeNull();
        descriptor!.DefinitionName.ShouldBe("Test.People");
        descriptor.EntityType.ShouldBe(typeof(Person));
        descriptor.Definition.ShouldBeOfType<PersonExportDefinition>();
    }

    [Fact]
    public void Find_is_ordinal_case_sensitive()
    {
        ExportPipelineRegistry registry = CreateRegistry(
            bindings: [new ExportEntityBinding<Person>(new PersonExportDefinition())]);

        registry.Find("test.people").ShouldBeNull();
        registry.Find("TEST.PEOPLE").ShouldBeNull();
        registry.Find("Test.People").ShouldNotBeNull();
    }

    [Fact]
    public void Find_unknown_name_returns_null()
    {
        ExportPipelineRegistry registry = CreateRegistry(
            bindings: [new ExportEntityBinding<Person>(new PersonExportDefinition())]);

        registry.Find("Does.Not.Exist").ShouldBeNull();
    }

    // ── Explicit vs auto composition ─────────────────────────────────────

    [Fact]
    public void Explicit_binding_wins_over_auto_definition_for_same_entity_type()
    {
        // Person has both an explicit definition and an auto source entry
        ExportPipelineRegistry registry = CreateRegistry(
            bindings: [new ExportEntityBinding<Person>(new PersonExportDefinition())],
            autoSources: [new FakeAutoSource(typeof(Person))]);

        IReadOnlyList<IExportPipelineDescriptor> all = registry.GetAll();

        all.Count.ShouldBe(1);
        all[0].DefinitionName.ShouldBe("Test.People");
        registry.Find("Auto.Person").ShouldBeNull();
    }

    [Fact]
    public void Auto_definitions_are_added_for_entity_types_without_explicit_binding()
    {
        ExportPipelineRegistry registry = CreateRegistry(
            bindings: [new ExportEntityBinding<Person>(new PersonExportDefinition())],
            autoSources: [new FakeAutoSource(typeof(Widget))]);

        IReadOnlyList<IExportPipelineDescriptor> all = registry.GetAll();

        all.Count.ShouldBe(2);
        all[0].DefinitionName.ShouldBe("Test.People"); // explicit first
        all[1].DefinitionName.ShouldBe("Auto.Widget");
        all[1].EntityType.ShouldBe(typeof(Widget));
        all[1].Definition.IsAutoGenerated.ShouldBeTrue();
    }

    [Fact]
    public void Duplicate_auto_entity_types_across_sources_are_deduplicated()
    {
        ExportPipelineRegistry registry = CreateRegistry(
            autoSources: [new FakeAutoSource(typeof(Widget)), new FakeAutoSource(typeof(Widget))]);

        registry.GetAll().Count.ShouldBe(1);
    }

    [Fact]
    public async Task Auto_descriptor_materializes_working_pipeline()
    {
        // Arrange — auto source + fake data source: the closed-generic descriptor produced at
        // registry initialization must create a pipeline that streams real rows.
        ExportPipelineRegistry registry = CreateRegistry(
            autoSources: [new FakeAutoSource(typeof(Widget))]);

        ServiceCollection services = new();
        services.AddSingleton<IExportDataSource<Widget>>(new WidgetDataSource());
        services.AddSingleton<IExtraExportFieldProvider>(new NullExtraExportFieldProvider());
        services.AddSingleton<IExportExtraValueResolver>(new NullExportExtraValueResolver());
        services.AddSingleton(Options.Create(new ExportOptions()));
        await using ServiceProvider provider = services.BuildServiceProvider();

        IExportPipelineDescriptor descriptor = registry.Find("Auto.Widget")!;
        IExportPipeline pipeline = descriptor.Create(provider);

        pipeline.DefinitionName.ShouldBe("Auto.Widget");
        pipeline.EntityType.ShouldBe(typeof(Widget));

        // Act — run the pipeline against a collecting writer
        IReadOnlyList<ExportFieldDescriptor> fields = descriptor.Definition.GetFields();
        CollectingExportWriter writer = new();
        ExportPipelineContext context = new()
        {
            Request = new ExportRequest("Auto.Widget", "csv", null, false, null, null, null, null),
            Fields = fields,
            Writer = writer,
        };

        await using MemoryStream output = new();
        long rowCount = await pipeline.WriteAsync(context, output, TestContext.Current.CancellationToken);

        // Assert
        rowCount.ShouldBe(2);
        writer.Rows.Count.ShouldBe(2);
        writer.Rows.ShouldAllBe(r => r.Length == fields.Count);
    }

    // ── Helpers ──────────────────────────────────────────────────────────

    private static ExportPipelineRegistry CreateRegistry(
        IReadOnlyList<IExportEntityBinding>? bindings = null,
        IReadOnlyList<IAutoExportDefinitionSource>? autoSources = null) =>
        new(bindings ?? [], autoSources ?? [], new NullExtraExportFieldProvider());

    private sealed class FakeAutoSource(params Type[] entityTypes) : IAutoExportDefinitionSource
    {
        public IReadOnlyList<Type> GetEntityTypes() => entityTypes;
    }

    private sealed class CollectingExportWriter : IExportWriter
    {
        public List<object?[]> Rows { get; } = [];

        public bool CanWrite(string format) => true;

        public string MimeType => "text/csv";

        public string FileExtension => ".csv";

        public async Task<long> WriteAsync(
            Stream output,
            IReadOnlyList<ExportFieldDescriptor> fields,
            IAsyncEnumerable<object?[]> rows,
            CancellationToken cancellationToken = default)
        {
            await foreach (object?[] row in rows.WithCancellation(cancellationToken))
            {
                Rows.Add(row);
            }

            return Rows.Count;
        }
    }

    // ── Test types ────────────────────────────────────────────────────────

    private sealed class Person
    {
        public string Name { get; set; } = string.Empty;
    }

    private sealed class Widget
    {
        public string Label { get; set; } = string.Empty;
        public int Quantity { get; set; }
    }

    private sealed class PersonExportDefinition : ExportDefinition<Person>
    {
        public override string Name => "Test.People";

        protected override void Configure(ExportDefinitionBuilder<Person> builder) =>
            builder.Field(p => p.Name);
    }

    private sealed class WidgetDataSource : IExportDataSource<Widget>
    {
        public IQueryable<Widget> GetQueryable() =>
            new List<Widget>
            {
                new() { Label = "Bolt", Quantity = 12 },
                new() { Label = "Nut", Quantity = 7 },
            }.AsQueryable();
    }
}
