using Granit.Invoicing.Domain;
using Granit.Invoicing.Dtos;

namespace Granit.Invoicing;

/// <summary>External accounting sync provider (Odoo, Sage, Stripe).</summary>
public interface IInvoiceSyncProvider
{
    /// <summary>Provider name (e.g., "odoo", "stripe").</summary>
    string Name { get; }

    /// <summary>Pushes invoice data to the external system.</summary>
    Task<(string ProviderName, string ExternalId)> SyncAsync(
        Invoice invoice, CancellationToken cancellationToken = default);

    /// <summary>Pulls status updates from the external system.</summary>
    Task<ExternalInvoiceStatus?> GetStatusAsync(
        InvoiceExternalReference reference, CancellationToken cancellationToken = default);

    /// <summary>Retrieves a document (PDF) generated by the external system.</summary>
    Task<Stream?> GetDocumentAsync(
        InvoiceExternalReference reference, CancellationToken cancellationToken = default);
}
