<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <PackageId>Granit.OpenIddict.Server</PackageId>
    <Description>OpenID Connect server configuration for Granit.OpenIddict. Endpoint URIs, flows, signing keys, custom grant types, and ASP.NET Core integration.</Description>
    <IsPackable>true</IsPackable>
  </PropertyGroup>

  <ItemGroup>
    <InternalsVisibleTo Include="Granit.OpenIddict.Server.Tests" />
    <InternalsVisibleTo Include="DynamicProxyGenAssembly2" />
  </ItemGroup>

  <ItemGroup>
    <FrameworkReference Include="Microsoft.AspNetCore.App" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="OpenIddict" />
    <PackageReference Include="OpenIddict.Server.AspNetCore" />
    <PackageReference Include="OpenIddict.Validation.AspNetCore" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Granit.Authentication\Granit.Authentication.csproj" />
    <ProjectReference Include="..\Granit.Authentication.DPoP\Granit.Authentication.DPoP.csproj" />
    <ProjectReference Include="..\Granit.OpenIddict\Granit.OpenIddict.csproj" />
    <ProjectReference Include="..\Granit.Identity.Abstractions\Granit.Identity.Abstractions.csproj" />
  </ItemGroup>

</Project>
