namespace Granit.Dashboards.Domain;

/// <summary>
/// Per-widget input record consumed by <see cref="Dashboard.Resync"/>. Mirrors
/// the constructor surface of <see cref="WidgetInstance"/> at the aggregate
/// boundary so external callers (the EFC orchestrator) can describe the
/// post-resync widget pool without holding a reference to the
/// <see langword="internal"/> <see cref="WidgetInstance.Create"/> factory.
/// </summary>
/// <param name="WidgetId">Identifier for the new <see cref="WidgetInstance"/> — generated by the orchestrator (kept stable across re-runs is not required, since slugs drive override carry-over).</param>
/// <param name="WidgetType">Widget kind discriminator (<c>"Kpi"</c>, <c>"Chart"</c>, …).</param>
/// <param name="Position">Dense-ranked grid order — comes from the source <c>WidgetDefinition.Position</c>.</param>
/// <param name="Width">Grid columns occupied — comes from the source <c>WidgetDefinition.Size.Width</c>.</param>
/// <param name="Height">Grid rows occupied — comes from the source <c>WidgetDefinition.Size.Height</c>.</param>
/// <param name="TitleLocalizationKey">Localization key (<c>"Widget:{DefinitionName}.{Slug}"</c>). Acts as the slug-equivalent for override carry-over since <c>DefinitionName</c> is invariant across a resync.</param>
/// <param name="ConfigJson">Kind-specific JSON config rebuilt from the descriptor.</param>
/// <param name="MetricName">Wire metric name for KPI widgets — <see langword="null"/> otherwise.</param>
/// <param name="QueryName">Wire query name for Chart / Table / Pivot widgets — <see langword="null"/> otherwise.</param>
/// <param name="RequiredPermission">Permission gate from the source widget — <see langword="null"/> when the widget inherits the metric / query permission.</param>
public sealed record ResyncWidgetInput(
    Guid WidgetId,
    string WidgetType,
    int Position,
    int Width,
    int Height,
    string TitleLocalizationKey,
    string ConfigJson,
    string? MetricName = null,
    string? QueryName = null,
    string? RequiredPermission = null);
