using Granit.DataExchange.Export;
using Shouldly;
using Xunit;

namespace Granit.DataExchange.Tests.Export;

public sealed class ReflectionExportDefinitionTests
{
    [Fact]
    public void Name_follows_auto_convention()
    {
        ReflectionExportDefinition definition = new(typeof(TestEntity));

        definition.Name.ShouldBe("Auto.TestEntity");
    }

    [Fact]
    public void EntityType_returns_configured_type()
    {
        ReflectionExportDefinition definition = new(typeof(TestEntity));

        definition.EntityType.ShouldBe(typeof(TestEntity));
    }

    [Fact]
    public void IsAutoGenerated_returns_true()
    {
        ReflectionExportDefinition definition = new(typeof(TestEntity));

        definition.IsAutoGenerated.ShouldBeTrue();
    }

    [Fact]
    public void QueryDefinitionName_returns_null()
    {
        ReflectionExportDefinition definition = new(typeof(TestEntity));

        definition.QueryDefinitionName.ShouldBeNull();
    }

    [Fact]
    public void SupportedFormats_returns_xlsx_and_csv()
    {
        ReflectionExportDefinition definition = new(typeof(TestEntity));

        definition.SupportedFormats.ShouldBe(["xlsx", "csv"]);
    }

    [Fact]
    public void GetFields_returns_exportable_properties()
    {
        ReflectionExportDefinition definition = new(typeof(TestEntity));

        IReadOnlyList<ExportFieldDescriptor> fields = definition.GetFields();

        fields.Count.ShouldBe(3);
        fields.ShouldContain(f => f.PropertyPath == "Id");
        fields.ShouldContain(f => f.PropertyPath == "Name");
        fields.ShouldContain(f => f.PropertyPath == "IsActive");
    }

    [Fact]
    public void GetFields_is_cached()
    {
        ReflectionExportDefinition definition = new(typeof(TestEntity));

        IReadOnlyList<ExportFieldDescriptor> first = definition.GetFields();
        IReadOnlyList<ExportFieldDescriptor> second = definition.GetFields();

        first.ShouldBeSameAs(second);
    }

    [Fact]
    public void Constructor_throws_for_null_type() =>
        Should.Throw<ArgumentNullException>(() => new ReflectionExportDefinition(null!));

    // ---- Test helpers ---------------------------------------------------

    private sealed class TestEntity
    {
        public Guid Id { get; set; }
        public string Name { get; set; } = string.Empty;
        public bool IsActive { get; set; }
        public List<string> Tags { get; set; } = []; // excluded (collection)
    }
}
