namespace Granit.Invoicing.Domain;

/// <summary>Reason an invoice was created.</summary>
public enum BillingReason
{
    /// <summary>First invoice for a new subscription.</summary>
    SubscriptionCreate = 0,

    /// <summary>Recurring billing cycle invoice.</summary>
    SubscriptionCycle = 1,

    /// <summary>Invoice generated by a subscription plan change (proration).</summary>
    SubscriptionUpdate = 2,

    /// <summary>Manually created invoice.</summary>
    Manual = 3,
}
