namespace Granit.MultiTenancy;

/// <summary>
/// Marks an endpoint as not requiring a tenant context. Endpoints decorated with this
/// attribute will not have the tenant header documented as a required parameter in
/// OpenAPI documents generated by <c>Granit.Http.ApiDocumentation</c>.
/// </summary>
[AttributeUsage(AttributeTargets.Class | AttributeTargets.Method, AllowMultiple = false)]
public sealed class AllowAnonymousTenantAttribute : Attribute;
