namespace Granit.Bff.Options;

/// <summary>
/// Client authentication method used by the BFF when communicating with the token endpoint.
/// </summary>
public enum BffClientAuthenticationMethod
{
    /// <summary>
    /// <c>client_secret_post</c> — sends <c>client_id</c> and <c>client_secret</c> in the POST body.
    /// This is the default and simplest method, but prohibited by FAPI 2.0.
    /// </summary>
    ClientSecretPost,

    /// <summary>
    /// <c>private_key_jwt</c> (RFC 7523) — sends a signed JWT assertion using the client's private key.
    /// Required for FAPI 2.0 conformance when not using mTLS.
    /// </summary>
    PrivateKeyJwt,
}

/// <summary>
/// Configuration options for the BFF security proxy.
/// Bind from <c>Bff</c> configuration section.
/// </summary>
/// <remarks>
/// Supports multiple frontends served from a single backend. Each frontend
/// has its own OIDC client, session cookie, scopes, and path prefix.
/// </remarks>
public sealed class GranitBffOptions
{
    /// <summary>Configuration section name.</summary>
    public const string SectionName = "Bff";

    /// <summary>OIDC authority URL (e.g., <c>https://auth.example.com</c>).</summary>
    public Uri Authority { get; set; } = null!;

    /// <summary>Session duration (default: 8 hours). After this, user must re-authenticate.</summary>
    public TimeSpan SessionDuration { get; set; } = TimeSpan.FromHours(8);

    /// <summary>Token refresh grace period (default: 1 minute before expiry).</summary>
    public TimeSpan RefreshGracePeriod { get; set; } = TimeSpan.FromMinutes(1);

    /// <summary>
    /// Gets or sets whether the session uses sliding expiration. When <see langword="true"/>,
    /// each proxied request past the halfway point extends the session.
    /// Default: <see langword="true"/>.
    /// </summary>
    public bool UseSessionSlidingExpiration { get; set; } = true;

    /// <summary>
    /// Gets or sets the absolute maximum session duration, even with sliding expiration.
    /// Prevents indefinite sessions (ISO 27001 A.9.4.2).
    /// Default: 8 hours.
    /// </summary>
    public TimeSpan SessionAbsoluteMaxDuration { get; set; } = TimeSpan.FromHours(8);

    /// <summary>
    /// Gets or sets whether the BFF validates the <c>iss</c> parameter in authorization
    /// responses (RFC 9207). Prevents IdP mix-up attacks.
    /// Default: <see langword="true"/>.
    /// </summary>
    public bool RequireIssuerValidation { get; set; } = true;

    /// <summary>
    /// Gets or sets the HMAC-SHA256 key for CSRF token generation, encoded as base64
    /// (256 bits = 32 bytes). When <see langword="null"/>, a random key is generated
    /// at startup — valid for single-instance deployments only.
    /// </summary>
    /// <remarks>
    /// In multi-instance deployments, all instances MUST share the same key so that a
    /// CSRF token generated by one instance is accepted by another. Provide this value
    /// via Vault or a secure environment variable.
    /// </remarks>
    public string? CsrfHmacKey { get; set; }

    /// <summary>
    /// Registered frontend applications. Each frontend has its own OIDC client,
    /// session cookie, and path prefix.
    /// </summary>
    /// <remarks>
    /// Example: Admin, Patient, Médecin, Mutuelle — each with different scopes
    /// and permissions but sharing the same backend API and identity provider.
    /// </remarks>
    public List<BffFrontendOptions> Frontends { get; set; } = [];
}

/// <summary>
/// Configuration for a single frontend application served by the BFF.
/// </summary>
#pragma warning disable GRSEC003 // Property name contains "Secret" — required configuration
public sealed class BffFrontendOptions
{
    /// <summary>Unique name for this frontend (e.g., <c>"admin"</c>, <c>"patient"</c>).</summary>
    public string Name { get; set; } = string.Empty;

    /// <summary>OIDC client ID (confidential client).</summary>
    public string ClientId { get; set; } = string.Empty;

    /// <summary>OIDC client secret.</summary>
    public string ClientSecret { get; set; } = string.Empty;

    /// <summary>
    /// Base URL of the frontend application when it runs on a separate origin
    /// (e.g., <c>"http://localhost:5173"</c> for a Vite dev server, or
    /// <c>"https://admin.example.com"</c> for a standalone deployment).
    /// When <see langword="null"/>, all redirect paths are relative (the frontend
    /// is served by the BFF itself).
    /// </summary>
    public string? ClientUrl { get; set; }

    /// <summary>OIDC scopes to request.</summary>
    public string[] Scopes { get; set; } = ["openid", "profile", "email", "roles", "offline_access"];

    /// <summary>
    /// URL path prefix for this frontend (e.g., <c>"/admin"</c>, <c>"/patient"</c>).
    /// </summary>
    /// <remarks>
    /// BFF endpoints are mounted under this prefix:
    /// <c>/{PathPrefix}/bff/login</c>, <c>/{PathPrefix}/bff/user</c>, etc.
    /// </remarks>
    public string PathPrefix { get; set; } = string.Empty;

    /// <summary>
    /// Path to the SPA static files for this frontend (e.g., <c>"wwwroot/admin"</c>).
    /// </summary>
    public string StaticFilesPath { get; set; } = string.Empty;

    /// <summary>
    /// Login page path within the frontend (default: <c>"/login"</c>).
    /// Combined with <see cref="ClientUrl"/> (when set) to produce the full login URL
    /// used by the OIDC authorization server to redirect unauthenticated users.
    /// </summary>
    public string LoginPath { get; set; } = "/login";

    /// <summary>Post-login redirect path (default: <c>"/"</c>, or <c>{ClientUrl}/</c> when set).</summary>
    public string? PostLoginRedirectPath { get; set; }

    /// <summary>Post-logout redirect path (default: <c>"/"</c>, or <c>{ClientUrl}/</c> when set).</summary>
    public string? PostLogoutRedirectPath { get; set; }

    /// <summary>
    /// Path to redirect to when the OIDC callback encounters an error. An <c>?error={code}</c>
    /// query parameter is appended so the SPA can display a localized error message.
    /// Default: <c>/login</c> (or <c>{ClientUrl}/login</c> when set).
    /// </summary>
    public string? ErrorRedirectPath { get; set; }

    /// <summary>
    /// Gets the session cookie name for this frontend.
    /// Production: <c>__Host-bff-{name}</c> (CSRF-hardened, requires HTTPS).
    /// Development: <c>.bff-{name}</c> (compatible with HTTP).
    /// Set automatically by <c>GranitBffEndpointsModule</c> based on the hosting environment.
    /// </summary>
    public string SessionCookieName => $"{CookiePrefix}bff-{Name}";

    /// <summary>Cookie name prefix, set by the module based on environment.</summary>
    internal string CookiePrefix { get; set; } = "__Host-";

    /// <summary>
    /// Gets the effective login URL. When <see cref="ClientUrl"/> is set, returns
    /// <c>{ClientUrl}{LoginPath}</c>; otherwise returns <see cref="LoginPath"/>.
    /// </summary>
    public string EffectiveLoginUrl => PrefixWithClientUrl(LoginPath);

    /// <summary>
    /// Gets the effective post-login redirect path.
    /// When <see cref="ClientUrl"/> is set and no explicit path is configured,
    /// returns <c>{ClientUrl}/</c>.
    /// </summary>
    public string EffectivePostLoginRedirectPath =>
        PostLoginRedirectPath ?? PrefixWithClientUrl(string.IsNullOrEmpty(PathPrefix) ? "/" : $"{PathPrefix}/");

    /// <summary>
    /// Gets the effective post-logout redirect path.
    /// When <see cref="ClientUrl"/> is set and no explicit path is configured,
    /// returns <c>{ClientUrl}/</c>.
    /// </summary>
    public string EffectivePostLogoutRedirectPath =>
        PostLogoutRedirectPath ?? PrefixWithClientUrl(string.IsNullOrEmpty(PathPrefix) ? "/" : $"{PathPrefix}/");

    /// <summary>
    /// Gets the effective error redirect path (without the <c>?error=</c> query parameter).
    /// When <see cref="ClientUrl"/> is set and no explicit path is configured,
    /// returns <c>{ClientUrl}/login</c>.
    /// </summary>
    public string EffectiveErrorRedirectPath =>
        ErrorRedirectPath ?? PrefixWithClientUrl(string.IsNullOrEmpty(PathPrefix) ? "/login" : $"{PathPrefix}/login");

    internal string PrefixWithClientUrl(string relativePath) =>
        string.IsNullOrEmpty(ClientUrl) ? relativePath : $"{ClientUrl.TrimEnd('/')}{relativePath}";

    /// <summary>
    /// Gets or sets a value indicating whether the BFF should use Pushed Authorization
    /// Requests (RFC 9126) when initiating the OIDC login flow.
    /// </summary>
    /// <remarks>
    /// When <see langword="true"/>, the BFF posts authorization parameters to the
    /// <c>/connect/par</c> endpoint and redirects the user with only the
    /// <c>request_uri</c>. Requires the OIDC server to support PAR.
    /// Default: <see langword="false"/>.
    /// </remarks>
    public bool UsePushedAuthorizationRequests { get; set; }

    /// <summary>
    /// Gets or sets a value indicating whether PAR (Pushed Authorization Requests)
    /// is mandatory. When <see langword="true"/>, a PAR failure returns 502 instead
    /// of falling back to direct authorization parameters.
    /// </summary>
    /// <remarks>
    /// Enable for FAPI 2.0 strict conformance. When <see langword="false"/>
    /// (default), PAR failure falls back to direct parameters for availability.
    /// Requires <see cref="UsePushedAuthorizationRequests"/> to be <see langword="true"/>.
    /// </remarks>
    public bool RequirePushedAuthorizationRequests { get; set; }

    /// <summary>
    /// Gets or sets a value indicating whether the BFF should use DPoP
    /// (Demonstrating Proof-of-Possession, RFC 9449) to bind tokens to a
    /// cryptographic key, preventing token replay attacks.
    /// </summary>
    /// <remarks>
    /// When <see langword="true"/>, the BFF generates an EC P-256 key pair per session,
    /// includes DPoP proofs in token requests and proxied API calls, and uses the
    /// <c>DPoP</c> token scheme instead of <c>Bearer</c>.
    /// Default: <see langword="false"/>.
    /// </remarks>
    public bool UseDPoP { get; set; }

    /// <summary>
    /// Gets or sets the client authentication method for token endpoint requests.
    /// </summary>
    /// <remarks>
    /// <para>Default: <see cref="BffClientAuthenticationMethod.ClientSecretPost"/>.</para>
    /// <para>
    /// Set to <see cref="BffClientAuthenticationMethod.PrivateKeyJwt"/> for FAPI 2.0
    /// conformance. Requires <see cref="ClientSigningKeyJwk"/> to be configured with
    /// the client's private key.
    /// </para>
    /// </remarks>
    public BffClientAuthenticationMethod ClientAuthenticationMethod { get; set; }
        = BffClientAuthenticationMethod.ClientSecretPost;

    /// <summary>
    /// Gets or sets the client's private signing key as a JWK JSON string.
    /// Required when <see cref="ClientAuthenticationMethod"/> is
    /// <see cref="BffClientAuthenticationMethod.PrivateKeyJwt"/>.
    /// </summary>
    /// <remarks>
    /// Supports EC (ES256) and RSA (PS256) keys. The JWK must include private key
    /// parameters (<c>d</c> for EC, <c>d</c>/<c>p</c>/<c>q</c> for RSA).
    /// </remarks>
    public string? ClientSigningKeyJwk { get; set; }
}
#pragma warning restore GRSEC003
