using Granit.BackgroundJobs.Abstractions;
using Granit.BackgroundJobs.Domain;
using Granit.BackgroundJobs.Internal;
using Granit.Timing;
using Microsoft.Extensions.DependencyInjection;
using Microsoft.Extensions.Logging;
using Wolverine.Runtime.Agents;

namespace Granit.BackgroundJobs.Wolverine.Internal;

/// <summary>
/// Wolverine singleton agent that initializes recurring job scheduling on cluster startup.
/// </summary>
/// <remarks>
/// <para>
/// URI: <c>granit-background-jobs://singleton</c> (generated by <see cref="SingularAgent"/>).
/// Wolverine guarantees that exactly one node in the cluster runs this agent at a time,
/// preventing duplicate scheduling on multi-node startup.
/// </para>
/// <para>
/// The agent outlives any request scope, so the Scoped store and dispatcher services are
/// resolved from a dedicated scope — never constructor-injected (captive dependency).
/// </para>
/// <para>
/// <b>Anti-doublon guarantee:</b> before scheduling a job, <see cref="startAsync"/> checks
/// whether <see cref="BackgroundJobDefinition.NextExecutionAt"/> is already in the future.
/// If it is, the job is already scheduled via the Outbox — no message is published.
/// </para>
/// </remarks>
internal sealed partial class CronSchedulerAgent(
    IServiceScopeFactory scopeFactory,
    IClock clock,
    ILogger<CronSchedulerAgent> logger) : SingularAgent("granit-background-jobs")
{
    /// <inheritdoc/>
    protected override async Task startAsync(CancellationToken cancellationToken)
    {
        await using AsyncServiceScope scope = scopeFactory.CreateAsyncScope();
        IBackgroundJobStoreReader storeReader =
            scope.ServiceProvider.GetRequiredService<IBackgroundJobStoreReader>();
        IBackgroundJobStoreWriter storeWriter =
            scope.ServiceProvider.GetRequiredService<IBackgroundJobStoreWriter>();
        IBackgroundJobDispatcher dispatcher =
            scope.ServiceProvider.GetRequiredService<IBackgroundJobDispatcher>();

        IReadOnlyList<BackgroundJobDefinition> jobs =
            await storeReader.GetEnabledJobsAsync(cancellationToken).ConfigureAwait(false);

        foreach (BackgroundJobDefinition job in jobs)
        {
            if (job.NextExecutionAt > clock.Now)
            {
                LogJobAlreadyScheduled(logger, job.JobName, job.NextExecutionAt.Value);
                continue;
            }

            DateTimeOffset? next = CronSchedulerHelper.ComputeNext(job.CronExpression, clock.Now);
            if (next is null)
            {
                LogJobCronInvalid(logger, job.JobName, job.CronExpression);
                continue;
            }

            object message = CronSchedulerHelper.CreateMessage(job.MessageType, job.JobName);
            await dispatcher.ScheduleAsync(message, next.Value, cancellationToken).ConfigureAwait(false);
            await storeWriter.RecordNextExecutionAsync(job.JobName, next.Value, cancellationToken).ConfigureAwait(false);
            LogJobScheduled(logger, job.JobName, next.Value);
        }
    }

    /// <inheritdoc/>
    protected override Task stopAsync(CancellationToken cancellationToken) => Task.CompletedTask;

    [LoggerMessage(Level = LogLevel.Debug,
        Message = "BackgroundJob '{JobName}' already scheduled for {Next} — skipping.")]
    private static partial void LogJobAlreadyScheduled(
        ILogger logger, string jobName, DateTimeOffset next);

    [LoggerMessage(Level = LogLevel.Warning,
        Message = "BackgroundJob '{JobName}' has invalid cron '{Cron}' — cannot schedule.")]
    private static partial void LogJobCronInvalid(
        ILogger logger, string jobName, string cron);

    [LoggerMessage(Level = LogLevel.Information,
        Message = "BackgroundJob '{JobName}' scheduled for first occurrence at {Next}.")]
    private static partial void LogJobScheduled(
        ILogger logger, string jobName, DateTimeOffset next);
}
