namespace Granit.Authentication.Oidc.DPoP;

/// <summary>
/// Generates DPoP (Demonstrating Proof-of-Possession) proofs as defined in RFC 9449.
/// DPoP binds access tokens to a specific client key pair, preventing token theft and replay.
/// </summary>
public interface IDPoPProofService
{
    /// <summary>
    /// Generates a new EC P-256 key pair and returns the private key as a JWK JSON string.
    /// </summary>
    /// <returns>A JSON string containing the private EC key in JWK format (with <c>"d"</c> parameter).</returns>
    string GenerateKeyPair();

    /// <summary>
    /// Creates a signed DPoP proof JWT for the given HTTP method and URI.
    /// </summary>
    /// <param name="privateKeyJwk">The private key as a JWK JSON string (generated by <see cref="GenerateKeyPair"/>).</param>
    /// <param name="httpMethod">The HTTP method (e.g., <c>"POST"</c>, <c>"GET"</c>).</param>
    /// <param name="httpUri">The target HTTP URI. Query string and fragment are stripped per RFC 9449 §4.3.</param>
    /// <param name="nonce">Optional server-provided nonce for replay protection (RFC 9449 §8).</param>
    /// <returns>A compact-serialized JWT string suitable for the <c>DPoP</c> HTTP header.</returns>
    string CreateProof(string privateKeyJwk, string httpMethod, string httpUri, string? nonce = null);
}
