<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <PackageId>Granit.MultiTenancy</PackageId>
    <Description>Multi-tenant management with current tenant resolution from JWT/Header, AsyncLocal context and ASP.NET Core middleware for Granit applications.</Description>
    <IsPackable>true</IsPackable>
  </PropertyGroup>

  <ItemGroup>
    <InternalsVisibleTo Include="Granit.MultiTenancy.Tests" />
  </ItemGroup>

  <ItemGroup>
    <FrameworkReference Include="Microsoft.AspNetCore.App" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Granit\Granit.csproj" />
  </ItemGroup>

</Project>
