using System.Diagnostics;
using System.Diagnostics.Metrics;

namespace Granit.Indexing.Embeddings.Diagnostics;

/// <summary>
/// OpenTelemetry metrics for the embeddings module. Meter:
/// <c>Granit.Indexing.Embeddings</c>.
/// </summary>
/// <remarks>
/// Counters carry a <c>tenant_id</c> tag coalesced to <c>"global"</c> when no tenant
/// context is active. Embedding content is NEVER tagged.
/// </remarks>
public sealed class EmbeddingsMetrics
{
    public const string MeterName = "Granit.Indexing.Embeddings";

    internal const string TenantIdTag = "tenant_id";
    internal const string GlobalTenant = "global";

    private readonly Counter<long> _embeddingsGenerated;
    private readonly Counter<long> _embeddingsFailed;
    private readonly Counter<long> _hybridSearchQueries;
    private readonly Histogram<double> _hybridSearchLatency;
    private readonly Counter<long> _vectorBackendMisses;

    public EmbeddingsMetrics(IMeterFactory meterFactory)
    {
        ArgumentNullException.ThrowIfNull(meterFactory);

        Meter meter = meterFactory.Create(MeterName);

        _embeddingsGenerated = meter.CreateCounter<long>(
            "granit.indexing.embeddings.generated",
            description: "Number of embeddings successfully generated by the configured IEmbeddingGenerator.");

        _embeddingsFailed = meter.CreateCounter<long>(
            "granit.indexing.embeddings.failed",
            description: "Number of embedding-generation failures (transport, timeout, deserialisation).");

        _hybridSearchQueries = meter.CreateCounter<long>(
            "granit.indexing.embeddings.hybrid.queries",
            description: "Number of search queries that ran through the hybrid (lexical + semantic) path.");

        _hybridSearchLatency = meter.CreateHistogram<double>(
            "granit.indexing.embeddings.hybrid.latency",
            unit: "s",
            description: "End-to-end hybrid search latency (both channels + fusion + slice).");

        _vectorBackendMisses = meter.CreateCounter<long>(
            "granit.indexing.embeddings.vector.misses",
            description: "Number of hybrid searches that returned zero hits from the vector channel (possible mapping / index drift).");
    }

    public void RecordEmbeddingGenerated(string? tenantId, string modelId)
    {
        TagList tags =
        [
            new(TenantIdTag, tenantId ?? GlobalTenant),
            new("model_id", string.IsNullOrEmpty(modelId) ? "unknown" : modelId),
        ];
        _embeddingsGenerated.Add(1, tags);
    }

    public void RecordEmbeddingFailed(string? tenantId, string reason)
    {
        TagList tags =
        [
            new(TenantIdTag, tenantId ?? GlobalTenant),
            new("reason", reason),
        ];
        _embeddingsFailed.Add(1, tags);
    }

    public void RecordHybridQuery(string? tenantId)
    {
        TagList tags = [new(TenantIdTag, tenantId ?? GlobalTenant)];
        _hybridSearchQueries.Add(1, tags);
    }

    public void RecordHybridLatency(string? tenantId, double durationSeconds)
    {
        TagList tags = [new(TenantIdTag, tenantId ?? GlobalTenant)];
        _hybridSearchLatency.Record(durationSeconds, tags);
    }

    public void RecordVectorBackendMiss(string? tenantId)
    {
        TagList tags = [new(TenantIdTag, tenantId ?? GlobalTenant)];
        _vectorBackendMisses.Add(1, tags);
    }
}
