using Granit.Http.ApiDocumentation.Scalar.Extensions;
using Granit.Modularity;

namespace Granit.Http.ApiDocumentation.Scalar;

/// <summary>
/// Granit module for the Scalar interactive API reference UI. Layers the Scalar UI
/// (with scoped CSP relaxation and OAuth2 popup support) on top of the OpenAPI
/// documents generated by <see cref="GranitHttpApiDocumentationModule"/>.
/// </summary>
/// <remarks>
/// Call <c>app.UseGranitApiDocumentation()</c> in <c>Program.cs</c> to expose
/// the OpenAPI JSON endpoints and the Scalar UI.
/// </remarks>
[DependsOn(
    typeof(GranitHttpApiDocumentationModule))]
public sealed class GranitHttpApiDocumentationScalarModule : GranitModule
{
    /// <inheritdoc/>
    public override void ConfigureServices(ServiceConfigurationContext context) =>
        context.Services.AddGranitApiDocumentationScalar();
}
