using System.Reflection;
using System.Text.RegularExpressions;
using Microsoft.AspNetCore.Http.Metadata;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.OpenApi;
using Microsoft.AspNetCore.Routing;
using Microsoft.OpenApi;

namespace Granit.Http.ApiDocumentation.Transformers;

/// <summary>
/// Normalizes Wolverine-generated OpenAPI operation metadata to respect standard ASP.NET Core attributes.
/// <list type="bullet">
///   <item><b>operationId</b>: overridden by the <c>Name</c> property of the Wolverine HTTP method
///     attribute (<c>[WolverinePost]</c>, etc.) when available.</item>
///   <item><b>description</b>: cleared when it matches the Wolverine auto-generated pattern
///     (<c>METHOD_path_segments</c>).</item>
///   <item><b>phantom 200</b>: removed when the endpoint declares explicit 2xx responses via
///     <c>[ProducesResponseType]</c> and the 200 response schema references <c>IResult</c>.</item>
/// </list>
/// </summary>
internal sealed partial class WolverineOpenApiOperationTransformer : IOpenApiOperationTransformer
{
    /// <inheritdoc/>
    public Task TransformAsync(
        OpenApiOperation operation,
        OpenApiOperationTransformerContext context,
        CancellationToken cancellationToken)
    {
        IList<object> metadata = context.Description.ActionDescriptor.EndpointMetadata;

        FixOperationId(operation, metadata);
        FixDescription(operation);
        FixPhantom200Response(operation, metadata);

        return Task.CompletedTask;
    }

    /// <summary>
    /// Overrides the auto-generated operationId with the endpoint name when available.
    /// Checks standard <see cref="EndpointNameMetadata"/> first, then falls back to reading
    /// the <c>Name</c> property from Wolverine HTTP method attributes via reflection
    /// (avoids compile-time dependency on Wolverine.Http).
    /// </summary>
    private static void FixOperationId(OpenApiOperation operation, IList<object> metadata)
    {
        // Standard ASP.NET Core EndpointNameMetadata (used by minimal APIs and Granit endpoints).
        string? endpointName = metadata.OfType<EndpointNameMetadata>()
            .FirstOrDefault()?.EndpointName;

        // Wolverine's HttpChain also implements IEndpointNameMetadata, but always returns
        // the auto-generated name. The user-specified Name from [WolverinePost(..., Name = "Xxx")]
        // is stored on the attribute itself. Read it via reflection to avoid a Wolverine dependency.
        if (string.IsNullOrEmpty(endpointName))
        {
            endpointName = GetWolverineAttributeName(metadata);
        }

        if (!string.IsNullOrEmpty(endpointName))
        {
            operation.OperationId = endpointName;
        }
    }

    /// <summary>
    /// Clears the description when it matches the Wolverine auto-generated pattern
    /// (<c>GET_api_v1_users_me</c>, <c>POST_api_v1_gdpr_export</c>, etc.).
    /// </summary>
    private static void FixDescription(OpenApiOperation operation)
    {
        if (operation.Description is null)
        {
            return;
        }

        if (AutoGeneratedPattern().IsMatch(operation.Description))
        {
            operation.Description = null;
        }
    }

    /// <summary>
    /// Removes the phantom 200 response when the endpoint explicitly declares other 2xx
    /// responses and the 200 schema references <c>IResult</c> (opaque Wolverine default).
    /// </summary>
    private static void FixPhantom200Response(OpenApiOperation operation, IList<object> metadata)
    {
        if (operation.Responses is null)
        {
            return;
        }

#pragma warning disable CA1854 // ContainsKey + indexer needed: TryGetValue returns IOpenApiResponse, Remove requires the key
        if (!operation.Responses.ContainsKey("200"))
        {
            return;
        }
#pragma warning restore CA1854

        List<int> explicit2xxCodes = GetExplicit2xxStatusCodes(metadata);

        // Only remove 200 if there are OTHER explicit 2xx codes (e.g. 202, 204)
        // and 200 was NOT explicitly declared.
        bool hasNon200Explicit = explicit2xxCodes.Any(code => code != 200);
        bool has200Explicit = explicit2xxCodes.Contains(200);

        if (!hasNon200Explicit || has200Explicit)
        {
            return;
        }

        if (IsPhantomIResultResponse(operation.Responses["200"]))
        {
            operation.Responses.Remove("200");
        }
    }

    /// <summary>
    /// Collects explicit 2xx status codes declared by the developer.
    /// Prefers <see cref="ProducesResponseTypeAttribute"/> (MVC attributes on Wolverine handlers)
    /// because Wolverine injects its own <see cref="IProducesResponseTypeMetadata"/> entries
    /// (200 + 404 by default) that do not reflect user intent. Falls back to
    /// <see cref="IProducesResponseTypeMetadata"/> for non-Wolverine (minimal API) endpoints
    /// where those metadata entries ARE user-declared.
    /// </summary>
    private static List<int> GetExplicit2xxStatusCodes(IList<object> metadata)
    {
        // ProducesResponseTypeAttribute (MVC) — user-declared on Wolverine handler methods.
        var mvcCodes = metadata.OfType<ProducesResponseTypeAttribute>()
            .Select(a => a.StatusCode)
            .Where(code => code is >= 200 and <= 299)
            .Distinct()
            .ToList();

        if (mvcCodes.Count > 0)
        {
            return mvcCodes;
        }

        // Fallback to IProducesResponseTypeMetadata for minimal API endpoints.
        return metadata.OfType<IProducesResponseTypeMetadata>()
            .Select(m => m.StatusCode)
            .Where(code => code is >= 200 and <= 299)
            .Distinct()
            .ToList();
    }

    /// <summary>
    /// Reads the <c>Name</c> property from a Wolverine HTTP method attribute
    /// (<c>WolverinePostAttribute</c>, etc.) via reflection to avoid a compile-time
    /// dependency on the Wolverine.Http package.
    /// </summary>
    private static string? GetWolverineAttributeName(IList<object> metadata)
    {
        foreach (object item in metadata)
        {
            Type type = item.GetType();
            if (type.FullName?.StartsWith("Wolverine.Http.Wolverine", StringComparison.Ordinal) != true)
            {
                continue;
            }

            PropertyInfo? nameProp = type.GetProperty("Name", BindingFlags.Public | BindingFlags.Instance);
            if (nameProp?.GetValue(item) is string name && !string.IsNullOrEmpty(name))
            {
                return name;
            }
        }

        return null;
    }

    private static bool IsPhantomIResultResponse(IOpenApiResponse response)
    {
        if (response is not OpenApiResponse { Content: { } content })
        {
            return false;
        }

        // OpenApiSchemaReference.Id returns null when hostDocument is null (transform-time).
        // The actual referenceId is stored in Reference.Id (via BaseOpenApiReference).
        return content.Values.Any(
            mt => mt.Schema is OpenApiSchemaReference schemaRef
                && schemaRef.Reference is { Id: "IResult" });
    }

    [GeneratedRegex(@"^(GET|POST|PUT|DELETE|PATCH|HEAD|OPTIONS)_")]
    private static partial Regex AutoGeneratedPattern();
}
