using Granit.Domain;

namespace Granit.DataExchange.Export;

/// <summary>
/// An auto-generated <see cref="IExportDefinitionDescriptor"/> built via reflection
/// from an entity type's public properties, filtered by
/// <see cref="ExportPropertyFilter"/>.
/// </summary>
/// <remarks>
/// <para>
/// This definition is used as a fallback when no explicit
/// <see cref="ExportDefinition{TEntity}"/> has been registered for the entity type.
/// Explicit definitions always take precedence.
/// </para>
/// <para>
/// When an <see cref="IExtraExportFieldProvider"/> is supplied and the entity implements
/// <see cref="IHasMetadata"/>, mapped extra properties are automatically appended
/// to the reflected fields.
/// </para>
/// <para>
/// The auto-generated name follows the convention <c>Auto.{EntityTypeName}</c>
/// (e.g. <c>Auto.Tenant</c>, <c>Auto.BlobDescriptor</c>).
/// </para>
/// </remarks>
internal sealed class ReflectionExportDefinition : IExportDefinitionDescriptor
{
    private readonly Lazy<IReadOnlyList<ExportFieldDescriptor>> _fields;
    private readonly bool _hasMetadata;

    /// <summary>
    /// Initializes a new instance for the specified entity type.
    /// </summary>
    /// <param name="entityType">The CLR entity type to introspect.</param>
    /// <param name="extraFieldProvider">
    /// Optional provider for extra property fields. When <see langword="null"/>,
    /// no extra properties are included.
    /// </param>
    internal ReflectionExportDefinition(Type entityType, IExtraExportFieldProvider? extraFieldProvider = null)
    {
        ArgumentNullException.ThrowIfNull(entityType);
        EntityType = entityType;
        _fields = new Lazy<IReadOnlyList<ExportFieldDescriptor>>(() => BuildFields(entityType, extraFieldProvider));
        _hasMetadata = typeof(IHasMetadata).IsAssignableFrom(entityType)
                              && extraFieldProvider is not null;
    }

    /// <inheritdoc/>
    public string Name => $"Auto.{EntityType.Name}";

    /// <inheritdoc/>
    public Type EntityType { get; }

    /// <inheritdoc/>
    public string? QueryDefinitionName => null;

    /// <inheritdoc/>
    public IReadOnlyList<string> SupportedFormats => ["xlsx", "csv"];

    /// <inheritdoc/>
    public bool IsAutoGenerated => true;

    /// <inheritdoc/>
    public bool IncludeMetadata => _hasMetadata;

    /// <inheritdoc/>
    public IReadOnlyList<ExportFieldDescriptor> GetFields() => _fields.Value;

    private static IReadOnlyList<ExportFieldDescriptor> BuildFields(
        Type entityType, IExtraExportFieldProvider? extraFieldProvider)
    {
        IReadOnlyList<ExportFieldDescriptor> clrFields = ExportPropertyFilter.BuildFields(entityType);

        if (extraFieldProvider is null || !typeof(IHasMetadata).IsAssignableFrom(entityType))
        {
            return clrFields;
        }

        IReadOnlyList<ExportFieldDescriptor> extraFields = extraFieldProvider.GetExtraFields(entityType);
        if (extraFields.Count == 0)
        {
            return clrFields;
        }

        List<ExportFieldDescriptor> merged = [.. clrFields, .. extraFields];
        return merged.AsReadOnly();
    }
}
