namespace Granit.DataExchange.Export;

/// <summary>
/// An auto-generated <see cref="IExportDefinitionDescriptor"/> built via reflection
/// from an entity type's public properties, filtered by
/// <see cref="ExportPropertyFilter"/>.
/// </summary>
/// <remarks>
/// <para>
/// This definition is used as a fallback when no explicit
/// <see cref="ExportDefinition{TEntity}"/> has been registered for the entity type.
/// Explicit definitions always take precedence.
/// </para>
/// <para>
/// The auto-generated name follows the convention <c>Auto.{EntityTypeName}</c>
/// (e.g. <c>Auto.Tenant</c>, <c>Auto.BlobDescriptor</c>).
/// </para>
/// </remarks>
internal sealed class ReflectionExportDefinition : IExportDefinitionDescriptor
{
    private readonly Lazy<IReadOnlyList<ExportFieldDescriptor>> _fields;

    /// <summary>
    /// Initializes a new instance for the specified entity type.
    /// </summary>
    /// <param name="entityType">The CLR entity type to introspect.</param>
    internal ReflectionExportDefinition(Type entityType)
    {
        ArgumentNullException.ThrowIfNull(entityType);
        EntityType = entityType;
        _fields = new Lazy<IReadOnlyList<ExportFieldDescriptor>>(
            () => ExportPropertyFilter.BuildFields(entityType));
    }

    /// <inheritdoc/>
    public string Name => $"Auto.{EntityType.Name}";

    /// <inheritdoc/>
    public Type EntityType { get; }

    /// <inheritdoc/>
    public string? QueryDefinitionName => null;

    /// <inheritdoc/>
    public IReadOnlyList<string> SupportedFormats => ["xlsx", "csv"];

    /// <inheritdoc/>
    public bool IsAutoGenerated => true;

    /// <inheritdoc/>
    public IReadOnlyList<ExportFieldDescriptor> GetFields() => _fields.Value;
}
