using System.Text.RegularExpressions;
using Shouldly;
using Xunit;

namespace Granit.ArchitectureTests;

/// <summary>
/// Detects common C# anti-patterns by scanning source files:
/// - async void methods (unhandled exceptions crash the process)
/// - throw ex; (destroys stack trace — use throw; instead)
/// </summary>
public sealed partial class SourceCodeAntiPatternTests
{
    private static readonly string RepoRoot = FindRepoRoot();

    [Fact]
    public void Async_void_methods_should_not_exist_in_src()
    {
        string srcDir = Path.Join(RepoRoot, "src");

        List<string> violations = [];

        foreach (string csFile in EnumerateSourceFiles(srcDir))
        {
            string content = File.ReadAllText(csFile);
            if (IsAutoGenerated(content))
            {
                continue;
            }

            foreach (Match match in AsyncVoidMethod().Matches(content))
            {
                string relativePath = Path.GetRelativePath(RepoRoot, csFile);
                int lineNumber = content[..match.Index].Count(c => c == '\n') + 1;
                violations.Add($"{relativePath}:{lineNumber}");
            }
        }

        violations.ShouldBeEmpty(
            "async void methods are forbidden — exceptions cannot be caught and will crash the process. " +
            "Use async Task instead. The only valid exception is event handlers, which do not exist in Granit. " +
            $"Violators: {string.Join(", ", violations)}");
    }

    [Fact]
    public void Throw_ex_should_not_be_used_in_src()
    {
        string srcDir = Path.Join(RepoRoot, "src");

        List<string> violations = [];

        foreach (string csFile in EnumerateSourceFiles(srcDir))
        {
            string content = File.ReadAllText(csFile);
            if (IsAutoGenerated(content))
            {
                continue;
            }

            foreach (Match match in ThrowExStatement().Matches(content))
            {
                string relativePath = Path.GetRelativePath(RepoRoot, csFile);
                int lineNumber = content[..match.Index].Count(c => c == '\n') + 1;
                violations.Add($"{relativePath}:{lineNumber}");
            }
        }

        violations.ShouldBeEmpty(
            "throw ex; destroys the original stack trace — use throw; to preserve it. " +
            $"Violators: {string.Join(", ", violations)}");
    }

    /// <summary>
    /// Namespace declarations must match the file's location on disk.
    /// Expected: {ProjectName}.{SubFolder1}.{SubFolder2} (dots replace path separators).
    /// Files at the module root should have namespace = project name.
    /// </summary>
    [Fact]
    public void Namespace_should_match_folder_structure_in_src()
    {
        string srcDir = Path.Join(RepoRoot, "src");

        List<string> violations = [];

        foreach (string csFile in EnumerateSourceFiles(srcDir))
        {
            string content = File.ReadAllText(csFile);
            if (IsAutoGenerated(content))
            {
                continue;
            }

            Match nsMatch = NamespaceDeclaration().Match(content);
            if (!nsMatch.Success)
            {
                continue;
            }

            string actualNamespace = nsMatch.Groups[1].Value;
            string expectedNamespace = ComputeExpectedNamespace(srcDir, csFile);

            if (!string.Equals(actualNamespace, expectedNamespace, StringComparison.Ordinal))
            {
                string relativePath = Path.GetRelativePath(RepoRoot, csFile);
                violations.Add($"{relativePath} (expected: {expectedNamespace}, actual: {actualNamespace})");
            }
        }

        violations.ShouldBeEmpty(
            "Namespace must match the folder structure: {ProjectName}.{SubFolder1}.{SubFolder2}. " +
            $"Violators: {string.Join(", ", violations)}");
    }

    /// <summary>
    /// Computes the expected namespace from a file's disk path.
    /// </summary>
    private static string ComputeExpectedNamespace(string srcRoot, string filePath)
    {
        // relativePath = "Granit.Foo/Internal/Bar.cs"
        string relativePath = Path.GetRelativePath(srcRoot, filePath);
        string[] parts = relativePath.Split(Path.DirectorySeparatorChar);

        // Strip organizational grouping folders (e.g. "bundles/") that are not part of the namespace.
        // Bundle projects live in src/bundles/Granit.Bundle.X/ but their namespace is Granit.Bundle.X.
        // Project directories always start with "Granit" — anything else is a grouping folder.
        if (parts.Length > 1 && !parts[0].StartsWith("Granit", StringComparison.Ordinal))
        {
            parts = parts[1..];
        }

        // parts[0] = project name, parts[1..^1] = subfolders, parts[^1] = filename
        string projectName = parts[0];

        // *.Abstractions packages use the parent namespace following the
        // Microsoft.Extensions.*.Abstractions convention (e.g.
        // Granit.QueryEngine.Abstractions → namespace Granit.QueryEngine).
        if (projectName.EndsWith(".Abstractions", StringComparison.Ordinal))
        {
            projectName = projectName[..^".Abstractions".Length];
        }

        if (parts.Length <= 2)
        {
            // File at module root: namespace = project name
            return projectName;
        }

        // Join project name + subfolders (skip filename)
        string subfolders = string.Join('.', parts[1..^1]);
        return $"{projectName}.{subfolders}";
    }

    /// <summary>
    /// Isolated DbContext classes in <c>*.EntityFrameworkCore</c> packages must follow the canonical pattern:
    /// <list type="bullet">
    /// <item><c>internal sealed class</c> (not <c>public</c>)</item>
    /// <item>Primary constructor with <c>DbContextOptions</c>, <c>ICurrentTenant?</c>, and <c>IDataFilter?</c></item>
    /// <item>Either inherits from <c>GranitDbContext</c> (preferred — gives the
    /// parameterised IMultiTenant filter) OR calls <c>ApplyGranitConventions</c>
    /// in <c>OnModelCreating</c> (legacy — only acceptable for DbContexts with
    /// no IMultiTenant entities).</item>
    /// </list>
    /// </summary>
    [Fact]
    public void DbContext_classes_should_follow_canonical_pattern()
    {
        string srcDir = Path.Join(RepoRoot, "src");

        List<string> violations = [];

        foreach (string csFile in EnumerateSourceFiles(srcDir, "*DbContext.cs"))
        {
            string fileName = Path.GetFileName(csFile);

            // Skip interfaces (I*DbContext.cs), factories, options, and extensions
            if (fileName.StartsWith('I')
                || fileName.Contains("Factory", StringComparison.Ordinal)
                || fileName.Contains("Options", StringComparison.Ordinal)
                || fileName.Contains("Extensions", StringComparison.Ordinal))
            {
                continue;
            }

            // GranitDbContext itself is the public base class — exempt from canonical-pattern rules.
            if (string.Equals(fileName, "GranitDbContext.cs", StringComparison.Ordinal))
            {
                continue;
            }

            // OpenIddictDbContext cannot inherit GranitDbContext (single-inheritance is taken
            // by IdentityDbContext<TUser,TRole,TKey>), so it inlines the parameterised
            // IMultiTenant filter and needs the tenant / data-filter references stored as
            // private fields for the lambda's closure. Exempt from the field-ban rule.
            if (string.Equals(fileName, "OpenIddictDbContext.cs", StringComparison.Ordinal))
            {
                continue;
            }

            // Only check *.EntityFrameworkCore packages (not *.Migrations — system DbContext without domain entities)
            string relativePath = Path.GetRelativePath(srcDir, csFile);
            string moduleName = relativePath.Split(Path.DirectorySeparatorChar)[0];
            if (!moduleName.Contains("EntityFrameworkCore", StringComparison.Ordinal))
            {
                continue;
            }

            string content = File.ReadAllText(csFile);
            if (IsAutoGenerated(content))
            {
                continue;
            }

            string relPath = Path.GetRelativePath(RepoRoot, csFile);

            // Must be internal sealed, not public
            if (content.Contains("public sealed class", StringComparison.Ordinal)
                || content.Contains("public class", StringComparison.Ordinal))
            {
                violations.Add($"{relPath} (must be 'internal sealed class', not 'public')");
            }

            // Must use primary constructor (no private fields for ICurrentTenant/IDataFilter)
            if (content.Contains("private readonly ICurrentTenant", StringComparison.Ordinal)
                || content.Contains("private readonly IDataFilter", StringComparison.Ordinal))
            {
                violations.Add($"{relPath} (use primary constructor instead of private fields for ICurrentTenant/IDataFilter)");
            }

            // Must wire Granit conventions — either by inheriting from GranitDbContext
            // (base class registers conventions + parameterised IMultiTenant filter) or
            // by calling ApplyGranitConventions directly (legacy).
            bool inheritsGranitDbContext = content.Contains(": GranitDbContext", StringComparison.Ordinal);
            bool callsApplyGranitConventions = content.Contains("ApplyGranitConventions", StringComparison.Ordinal);
            if (!inheritsGranitDbContext && !callsApplyGranitConventions)
            {
                violations.Add($"{relPath} (must inherit from GranitDbContext or call modelBuilder.ApplyGranitConventions in OnModelCreating)");
            }
        }

        violations.ShouldBeEmpty(
            "Isolated DbContext classes must follow the canonical pattern: " +
            "internal sealed class, primary constructor with ICurrentTenant/IDataFilter?, " +
            "inheriting from GranitDbContext (preferred) or calling ApplyGranitConventions. " +
            $"Violators: {string.Join("; ", violations)}");
    }

    /// <summary>
    /// Direct calls to <c>IResponseCookies.Append()</c> or <c>IResponseCookies.Delete()</c>
    /// bypass the Strict Registry Pattern and GDPR consent checks enforced by
    /// <c>IGranitCookieManager</c>. Only <c>GranitCookieManager</c> (the manager implementation
    /// itself) is allowed to call these methods directly.
    /// Complements the <c>GRSEC004</c> Roslyn analyzer which is opt-in per project.
    /// </summary>
    [Fact]
    public void Direct_IResponseCookies_access_should_only_be_in_GranitCookieManager()
    {
        string srcDir = Path.Combine(RepoRoot, "src");

        List<string> violations = [];

        foreach (string csFile in EnumerateSourceFiles(srcDir))
        {
            // Only GranitCookieManager.cs is allowed to call Response.Cookies directly
            if (Path.GetFileName(csFile) == "GranitCookieManager.cs")
            {
                continue;
            }

            string content = File.ReadAllText(csFile);
            if (IsAutoGenerated(content))
            {
                continue;
            }

            foreach (Match match in DirectCookieAccess().Matches(content))
            {
                // Skip matches inside pragma disable GRSEC004 blocks (already suppressed intentionally)
                string precedingText = content[..match.Index];
                if (precedingText.Contains("#pragma warning disable GRSEC004", StringComparison.Ordinal)
                    && !precedingText.Contains("#pragma warning restore GRSEC004", StringComparison.Ordinal))
                {
                    continue;
                }

                string relativePath = Path.GetRelativePath(RepoRoot, csFile);
                int lineNumber = content[..match.Index].Count(c => c == '\n') + 1;
                violations.Add($"{relativePath}:{lineNumber}");
            }
        }

        violations.ShouldBeEmpty(
            "Direct calls to Response.Cookies.Append() / Delete() bypass the Strict Registry Pattern "
            + "and GDPR consent checks. Use IGranitCookieManager.SetCookieAsync() or DeleteCookie() instead. "
            + "If this is the cookie manager implementation itself, name the file GranitCookieManager.cs. "
            + $"Violators: {string.Join(", ", violations)}");
    }

    /// <summary>
    /// Parameterless <c>IgnoreQueryFilters()</c> disables ALL query filters — including the
    /// multi-tenant filter — creating a cross-tenant data leak risk.
    /// Use named filters instead: <c>.IgnoreQueryFilters([GranitFilterNames.SoftDelete])</c>.
    /// Only <c>DbContextPurgeExtensions.cs</c> is exempt (intentional global archival).
    /// </summary>
    [Fact]
    public void IgnoreQueryFilters_without_named_filter_should_not_exist_in_src()
    {
        string srcDir = Path.Join(RepoRoot, "src");

        // DbContextPurgeExtensions intentionally bypasses all filters for global archival (ISO 27001).
        HashSet<string> allowedFiles = ["DbContextPurgeExtensions.cs"];

        List<string> violations = [];

        foreach (string csFile in EnumerateSourceFiles(srcDir))
        {
            if (allowedFiles.Contains(Path.GetFileName(csFile)))
            {
                continue;
            }

            string content = File.ReadAllText(csFile);
            if (IsAutoGenerated(content))
            {
                continue;
            }

            foreach (Match match in ParameterlessIgnoreQueryFilters().Matches(content))
            {
                string relativePath = Path.GetRelativePath(RepoRoot, csFile);
                int lineNumber = content[..match.Index].Count(c => c == '\n') + 1;
                violations.Add($"{relativePath}:{lineNumber}");
            }
        }

        violations.ShouldBeEmpty(
            "Parameterless .IgnoreQueryFilters() disables ALL query filters including multi-tenant isolation, "
            + "creating a cross-tenant data leak risk. Use named filters instead: "
            + ".IgnoreQueryFilters([GranitFilterNames.SoftDelete]). "
            + $"Violators: {string.Join(", ", violations)}");
    }

    /// <summary>
    /// Ensures test projects do not define local <c>ICurrentTenant</c> implementations.
    /// <c>Granit.Testing.Fakes.FakeCurrentTenant</c> is the canonical substitute —
    /// AsyncLocal-safe, fully mutable, and reusable across every test project.
    /// </summary>
    [Fact]
    public void Test_projects_should_not_define_local_ICurrentTenant_implementations()
    {
        string testsDir = Path.Join(RepoRoot, "tests");

        // Granit.Testing is the canonical home for ICurrentTenant test doubles — exempt it.
        // ArchitectureTests is exempt because its regex/comment strings contain the pattern.
        HashSet<string> allowedProjects =
        [
            Path.Join(testsDir, "Granit.Testing.Tests"),
            Path.Join(testsDir, "Granit.ArchitectureTests"),
        ];

        List<string> violations = [];

        foreach (string csFile in EnumerateSourceFiles(testsDir))
        {
            if (allowedProjects.Any(p => csFile.StartsWith(p, StringComparison.OrdinalIgnoreCase)))
            {
                continue;
            }

            string content = File.ReadAllText(csFile);
            if (IsAutoGenerated(content))
            {
                continue;
            }

            if (LocalICurrentTenantImpl().IsMatch(content))
            {
                violations.Add(Path.GetRelativePath(RepoRoot, csFile));
            }
        }

        violations.ShouldBeEmpty(
            "Test files must not define local ICurrentTenant implementations. "
            + "Use Granit.Testing.Fakes.FakeCurrentTenant instead. "
            + $"Violators: {string.Join(", ", violations)}");
    }

    /// <summary>
    /// The webhook delivery <c>SocketsHttpHandler</c> targets customer-controlled URLs at an
    /// untrusted egress boundary. It MUST suppress W3C trace-context propagation
    /// (<c>ActivityHeadersPropagator = null</c>) so internal traceparent/tracestate headers never
    /// leak our topology (VULN-100-OBS), and MUST disable auto-redirect
    /// (<c>AllowAutoRedirect = false</c>) so a 3xx cannot bypass the SSRF ConnectCallback nor mask a
    /// delivery failure (VULN-300-infra). This source-regex guard lives in the architecture shard so
    /// the convention is enforced repo-wide even if the Webhooks unit tests are skipped or the module
    /// is refactored; a companion runtime probe (<c>WebhookDeliveryEgressTests</c>) asserts the same
    /// two settings on the actual DI-configured handler instance.
    /// </summary>
    [Fact]
    public void Webhook_delivery_handler_must_suppress_trace_propagation_and_auto_redirect()
    {
        string handlerFile = Path.Join(
            RepoRoot, "src", "Granit.Webhooks", "Extensions", "WebhooksHostApplicationBuilderExtensions.cs");

        File.Exists(handlerFile).ShouldBeTrue(
            $"Expected webhook egress configuration at {handlerFile}. If the file moved, update this guard.");

        string content = File.ReadAllText(handlerFile);

        WebhookNullsActivityHeadersPropagator().IsMatch(content).ShouldBeTrue(
            "Webhook delivery SocketsHttpHandler must set 'ActivityHeadersPropagator = null' to stop "
            + "leaking internal W3C trace context (traceparent/tracestate) to customer-controlled "
            + "webhook URLs (VULN-100-OBS). Re-enabling propagation is a topology-disclosure regression.");

        WebhookDisablesAutoRedirect().IsMatch(content).ShouldBeTrue(
            "Webhook delivery SocketsHttpHandler must set 'AllowAutoRedirect = false' — a 3xx from a "
            + "subscriber is a delivery failure, and following it would bypass the SSRF ConnectCallback "
            + "(VULN-300-infra).");
    }

    private static string FindRepoRoot()
    {
        string? dir = Path.GetDirectoryName(typeof(SourceCodeAntiPatternTests).Assembly.Location);
        while (dir is not null)
        {
            string gitPath = Path.Join(dir, ".git");
            if (Directory.Exists(gitPath) || File.Exists(gitPath))
            {
                return dir;
            }

            dir = Path.GetDirectoryName(dir);
        }

        throw new InvalidOperationException("Could not find repository root (.git directory)");
    }

    /// <summary>
    /// Enumerates authored C# source files under <paramref name="root"/>, excluding build
    /// output (<c>bin/</c>, <c>obj/</c>). Auto-generated files are not filtered here — that
    /// needs the file content; callers skip them via <see cref="IsAutoGenerated"/>.
    /// </summary>
    private static IEnumerable<string> EnumerateSourceFiles(string root, string searchPattern = "*.cs")
    {
        foreach (string csFile in Directory.GetFiles(root, searchPattern, SearchOption.AllDirectories))
        {
            if (csFile.Contains(Path.DirectorySeparatorChar + "bin" + Path.DirectorySeparatorChar, StringComparison.Ordinal)
                || csFile.Contains(Path.DirectorySeparatorChar + "obj" + Path.DirectorySeparatorChar, StringComparison.Ordinal))
            {
                continue;
            }

            yield return csFile;
        }
    }

    /// <summary>
    /// True when the file begins with a Roslyn/JasperFx auto-generated marker
    /// (<c>// &lt;auto-generated/&gt;</c>). Wolverine <c>codegen write</c> emits handler code
    /// into <c>Internal/Generated/</c> under the host project — these files live in <c>src/</c>
    /// but are machine-generated and must not be held to authored-code conventions
    /// (namespace shape, async-void, throw-ex, etc.). The marker is required to sit in the
    /// file header (first few lines), matching how generators emit it.
    /// </summary>
    private static bool IsAutoGenerated(string content)
    {
        using StringReader reader = new(content);
        for (int i = 0; i < 5; i++)
        {
            string? line = reader.ReadLine();
            if (line is null)
            {
                break;
            }

            if (line.Contains("<auto-generated", StringComparison.Ordinal))
            {
                return true;
            }
        }

        return false;
    }

    /// <summary>
    /// Matches "async void MethodName" — excludes comments (lines starting with ///).
    /// Requires whitespace before async (indentation) to avoid matching inside string literals.
    /// </summary>
    [GeneratedRegex(@"(?<=^[ \t]+(?:(?:public|private|protected|internal|static|override|sealed|virtual|new)\s+)*)async\s+void\s+\w+", RegexOptions.Multiline)]
    private static partial Regex AsyncVoidMethod();

    /// <summary>
    /// Matches "throw identifier;" where identifier is NOT "new" (which would be throw new ...).
    /// This catches "throw ex;" and "throw exception;" patterns that destroy stack traces.
    /// </summary>
    [GeneratedRegex(@"\bthrow\s+(?!new\b)[a-zA-Z_]\w*\s*;")]
    private static partial Regex ThrowExStatement();

    /// <summary>
    /// Matches file-scoped namespace (<c>namespace X.Y.Z;</c>) or block-scoped
    /// (<c>namespace X.Y.Z {</c>). Captures the namespace identifier.
    /// </summary>
    [GeneratedRegex(@"^namespace\s+([\w.]+)\s*[;{]", RegexOptions.Multiline)]
    private static partial Regex NamespaceDeclaration();

    /// <summary>
    /// Matches direct calls to <c>.Cookies.Append(</c> or <c>.Cookies.Delete(</c>
    /// on response objects. Captures both <c>Response.Cookies.*</c> and variables
    /// holding <c>IResponseCookies</c>.
    /// </summary>
    [GeneratedRegex(@"\.Cookies\.(Append|Delete)\s*\(")]
    private static partial Regex DirectCookieAccess();

    /// <summary>
    /// Matches parameterless <c>.IgnoreQueryFilters()</c> — the form that disables ALL
    /// query filters. Does NOT match <c>.IgnoreQueryFilters([...])</c> or
    /// <c>.IgnoreQueryFilters(filterName)</c> which are the safe named-filter forms.
    /// </summary>
    [GeneratedRegex(@"\.IgnoreQueryFilters\(\)")]
    private static partial Regex ParameterlessIgnoreQueryFilters();

    /// <summary>
    /// Matches a class declaration that directly implements <c>ICurrentTenant</c>
    /// (e.g. <c>class Foo : ICurrentTenant</c> or <c>class Foo : IBar, ICurrentTenant</c>).
    /// </summary>
    [GeneratedRegex(@"\bclass\s+\w+[^{]*:\s*[^{]*\bICurrentTenant\b")]
    private static partial Regex LocalICurrentTenantImpl();

    /// <summary>
    /// Matches <c>ActivityHeadersPropagator = null</c> on the webhook delivery handler —
    /// the egress guard that stops internal trace-context leaking to customer URLs.
    /// </summary>
    [GeneratedRegex(@"ActivityHeadersPropagator\s*=\s*null")]
    private static partial Regex WebhookNullsActivityHeadersPropagator();

    /// <summary>
    /// Matches <c>AllowAutoRedirect = false</c> on the webhook delivery handler —
    /// a subscriber 3xx is a delivery failure, never a redirect to follow.
    /// </summary>
    [GeneratedRegex(@"AllowAutoRedirect\s*=\s*false")]
    private static partial Regex WebhookDisablesAutoRedirect();
}
