using Granit.DataProtection;
using Granit.Domain;
using Granit.MultiTenancy;

namespace Granit.Identity.Domain;

/// <summary>
/// Canonical user aggregate per ADR-051. Replaces the dual hierarchy
/// <c>GranitUser</c> (local) / <c>UserCacheEntry</c> (federated) at the
/// "who is this person" level — auth-secret storage and IdP-cache fields
/// live in their own siblings (<c>LocalIdentity</c> / <c>FederatedIdentity</c>)
/// that reference <see cref="Id"/> via FK.
/// </summary>
/// <remarks>
/// <para>
/// The aggregate is owned by <c>Granit.Identity</c> (foundation module) so
/// every Granit app has it without taking on extra dependencies. Tiny apps
/// without <c>Granit.Parties</c> still work; the optional
/// <c>Granit.Identity.Parties</c> bridge auto-creates a Party of kind
/// <c>Person</c> when both modules are loaded (per ADR-051's bridge contract).
/// </para>
/// <para>
/// Implements <see cref="IIdentityUser"/> so existing consumers
/// (<see cref="IUserLookupService"/>, <see cref="IIdentityUserReader"/>,
/// audit projections) see it interchangeably with the legacy
/// <c>GranitUser</c> / <c>UserCacheEntry</c> implementations during the
/// staged migration.
/// </para>
/// </remarks>
public sealed class User : AuditedAggregateRoot, IIdentityUser, IMultiTenant
{
    /// <summary>EF Core constructor.</summary>
    private User() { }

    /// <summary>Wire identifier for the user (string view per <see cref="IIdentityUser.UserId"/>) — coerces <see cref="Entity.Id"/> to string.</summary>
    string IIdentityUser.UserId => Id.ToString();

    /// <summary>
    /// Display label used in references and list rows
    /// (<c>EntityDefinition.DisplayProperty</c> per ADR-040). Free-form text
    /// — typically <c>FirstName + " " + LastName</c> or a tenant-curated
    /// label.
    /// </summary>
    [SensitiveData]
    public string DisplayName { get; private set; } = string.Empty;

    /// <summary>
    /// Login email and primary contact. Required at creation (used by
    /// recovery flows). Sync-target of <see cref="IIdentityUser.Username"/>
    /// where the local backend imposes a username-equals-email convention.
    /// </summary>
    [SensitiveData(Level = Sensitivity.Confidential)]
    public string Email { get; private set; } = string.Empty;

    /// <summary>Given name (optional).</summary>
    [SensitiveData]
    public string? FirstName { get; private set; }

    /// <summary>Family name (optional).</summary>
    [SensitiveData]
    public string? LastName { get; private set; }

    /// <summary>E.164 phone number (optional).</summary>
    [SensitiveData(Level = Sensitivity.Confidential)]
    public string? PhoneNumber { get; private set; }

    /// <summary>BCP-47 culture preferred by the user (e.g. <c>"en-GB"</c>, <c>"fr"</c>).</summary>
    public string? PreferredLocale { get; private set; }

    /// <summary>IANA timezone identifier (e.g. <c>"Europe/Brussels"</c>).</summary>
    public string? Timezone { get; private set; }

    /// <summary>
    /// Account-level toggle. <see langword="false"/> disables sign-in for
    /// every linked identity link (local + federated). Independent from the
    /// per-link <c>EmailConfirmed</c> / <c>LockoutEnd</c> security counters
    /// — those live on <c>LocalIdentity</c>.
    /// </summary>
    public bool IsEnabled { get; private set; } = true;

    /// <summary>Tenant identifier, or <see langword="null"/> for cross-tenant / host-side users.</summary>
    public Guid? TenantId { get; set; }

    /// <inheritdoc cref="IIdentityUser.Username"/>
    string? IIdentityUser.Username => Email;

    /// <inheritdoc cref="IIdentityUser.Enabled"/>
    bool IIdentityUser.Enabled => IsEnabled;

    /// <inheritdoc cref="IIdentityUser.Metadata"/>
    /// <remarks>
    /// Empty by default. The <c>Granit.Identity.EntityFrameworkCore</c>
    /// companion package layers a <c>CustomAttributesJson</c> column +
    /// resolver in a follow-up step (B-step 1.5); the abstraction shape
    /// here is stable.
    /// </remarks>
    IReadOnlyDictionary<string, string> IIdentityUser.Metadata =>
        EmptyMetadata;

    private static readonly IReadOnlyDictionary<string, string> EmptyMetadata =
        new Dictionary<string, string>(StringComparer.Ordinal);

    /// <summary>
    /// Factory — the only way to construct a new <see cref="User"/>.
    /// Callers (the local-side ASP.NET Identity wiring, the federated-side
    /// cache hydration, the bridge handlers) come through here so the
    /// invariants stay enforced.
    /// </summary>
    /// <param name="id">Stable identifier — typically generated by the framework's <see cref="Granit.Guids.IGuidGenerator"/>.</param>
    /// <param name="email">Required login email.</param>
    /// <param name="displayName">Required display label.</param>
    /// <param name="firstName">Optional given name.</param>
    /// <param name="lastName">Optional family name.</param>
    /// <param name="phoneNumber">Optional E.164 phone.</param>
    /// <param name="tenantId">Tenant scope.</param>
    public static User Create(
        Guid id,
        string email,
        string displayName,
        string? firstName = null,
        string? lastName = null,
        string? phoneNumber = null,
        Guid? tenantId = null)
    {
        ArgumentException.ThrowIfNullOrWhiteSpace(email);
        ArgumentException.ThrowIfNullOrWhiteSpace(displayName);

        User user = new()
        {
            Id = id,
            Email = email,
            DisplayName = displayName,
            FirstName = firstName,
            LastName = lastName,
            PhoneNumber = phoneNumber,
            TenantId = tenantId,
            IsEnabled = true,
        };
        return user;
    }

    /// <summary>
    /// Updates the user's profile fields. Producers of
    /// <see cref="Events.IdentityUserProfileUpdatedEto"/> call here from
    /// the local sync handler (when the underlying ASP.NET Identity user
    /// changes) and the federated sync handler (when the IdP claims
    /// refresh).
    /// </summary>
    public void UpdateProfile(
        string displayName,
        string email,
        string? firstName,
        string? lastName,
        string? phoneNumber,
        string? preferredLocale,
        string? timezone)
    {
        ArgumentException.ThrowIfNullOrWhiteSpace(displayName);
        ArgumentException.ThrowIfNullOrWhiteSpace(email);

        DisplayName = displayName;
        Email = email;
        FirstName = firstName;
        LastName = lastName;
        PhoneNumber = phoneNumber;
        PreferredLocale = preferredLocale;
        Timezone = timezone;
    }

    /// <summary>Enables sign-in for the user.</summary>
    public void Enable() => IsEnabled = true;

    /// <summary>Disables sign-in for the user. Linked <c>LocalIdentity</c> and <c>FederatedIdentity</c> records survive — only the gate flips.</summary>
    public void Disable() => IsEnabled = false;
}
