using Granit.DataExchange.Export;

namespace Granit.DataExchange.Endpoints.Dtos.Export;

/// <summary>
/// Response DTO for an export definition summary.
/// </summary>
public sealed record ExportDefinitionResponse(
    string Name,
    string EntityType,
    IReadOnlyList<string> SupportedFormats,
    bool IsAutoGenerated)
{
    /// <summary>
    /// Maps an <see cref="IExportDefinitionDescriptor"/> to a response DTO,
    /// filtering <see cref="SupportedFormats"/> to only include formats
    /// for which an <see cref="IExportWriter"/> is registered.
    /// </summary>
    internal static ExportDefinitionResponse FromDescriptor(
        IExportDefinitionDescriptor descriptor,
        IReadOnlyList<IExportWriter> writers)
    {
        IReadOnlyList<string> formats = descriptor.SupportedFormats
            .Where(f => writers.Any(w => w.CanWrite(f)))
            .ToList()
            .AsReadOnly();

        return new(descriptor.Name, descriptor.EntityType.Name, formats, descriptor.IsAutoGenerated);
    }
}
