using System.Security.Cryptography;
using Microsoft.Extensions.Logging;

namespace Granit.Privacy.DataExport.Security;

/// <summary>
/// In-memory AES-256-GCM <see cref="IExportContentEncryptor"/> using a single key
/// generated at construction time. Suitable for development, tests, and single-instance
/// deployments where an encrypted SAR package does not need to survive a process restart.
/// Production deployments MUST override this with a Vault-backed implementation whose key
/// lives in Vault (see the startup guard that fails closed outside <c>Development</c>).
/// </summary>
/// <remarks>
/// <para>
/// The 256-bit key is generated by <see cref="RandomNumberGenerator.GetBytes(int)"/> at
/// construction. This mirrors <see cref="EphemeralExportHmacSigner"/>'s key lifecycle
/// exactly so the two ephemeral primitives share the same operational caveat: a package
/// encrypted by one process cannot be decrypted by another, which is why hosts running
/// outside <c>Development</c> must register a shared-state (Vault-backed) encryptor before
/// startup.
/// </para>
/// <para>
/// Ciphertext layout is <c>[12-byte nonce][16-byte tag][ciphertext]</c> — a fresh random
/// nonce per <see cref="Encrypt"/> call, the GCM authentication tag next, then the
/// ciphertext. The layout is self-describing so decrypt needs no side-channel state.
/// </para>
/// </remarks>
public sealed partial class EphemeralExportContentEncryptor : IExportContentEncryptor, IDisposable
{
    private const int NonceSizeBytes = 12;
    private const int TagSizeBytes = 16;
    private const int KeySizeBytes = 32;
    private const int OverheadBytes = NonceSizeBytes + TagSizeBytes;

    private readonly byte[] _key;
    private readonly ILogger<EphemeralExportContentEncryptor> _logger;
    private bool _disposed;

    /// <summary>Creates an encryptor with a fresh random 256-bit key.</summary>
    public EphemeralExportContentEncryptor(ILogger<EphemeralExportContentEncryptor> logger)
    {
        ArgumentNullException.ThrowIfNull(logger);
        _logger = logger;
        _key = RandomNumberGenerator.GetBytes(KeySizeBytes);
        LogEphemeralKeyGenerated(_logger, KeySizeBytes * 8);
    }

    /// <inheritdoc />
    public byte[] Encrypt(ReadOnlySpan<byte> plaintext)
    {
        ObjectDisposedException.ThrowIf(_disposed, this);

        byte[] result = new byte[OverheadBytes + plaintext.Length];
        Span<byte> nonce = result.AsSpan(0, NonceSizeBytes);
        Span<byte> tag = result.AsSpan(NonceSizeBytes, TagSizeBytes);
        Span<byte> ciphertext = result.AsSpan(OverheadBytes);

        RandomNumberGenerator.Fill(nonce);

        using AesGcm aesGcm = new(_key, TagSizeBytes);
        aesGcm.Encrypt(nonce, plaintext, ciphertext, tag);

        return result;
    }

    /// <inheritdoc />
    public byte[] Decrypt(ReadOnlySpan<byte> ciphertext)
    {
        ObjectDisposedException.ThrowIf(_disposed, this);

        if (ciphertext.Length < OverheadBytes)
        {
            throw new ArgumentException(
                $"Invalid export ciphertext: minimum {OverheadBytes} bytes required (nonce + tag), "
                + $"received {ciphertext.Length} bytes.",
                nameof(ciphertext));
        }

        ReadOnlySpan<byte> nonce = ciphertext[..NonceSizeBytes];
        ReadOnlySpan<byte> tag = ciphertext.Slice(NonceSizeBytes, TagSizeBytes);
        ReadOnlySpan<byte> cipher = ciphertext[OverheadBytes..];

        byte[] plaintext = new byte[cipher.Length];
        using AesGcm aesGcm = new(_key, TagSizeBytes);
        // AesGcm.Decrypt validates the authentication tag first and throws
        // CryptographicException on mismatch WITHOUT writing plaintext — tamper detection
        // happens before any bytes are exposed.
        aesGcm.Decrypt(nonce, cipher, tag, plaintext);

        return plaintext;
    }

    /// <inheritdoc />
    public void Dispose()
    {
        if (_disposed)
        {
            return;
        }

        CryptographicOperations.ZeroMemory(_key);
        _disposed = true;
    }

    [LoggerMessage(Level = LogLevel.Warning,
        Message = "Privacy export content encryption: ephemeral {KeyBits}-bit AES-GCM key generated. "
                  + "Encrypted SAR packages will not survive a process restart. "
                  + "Register a production IExportContentEncryptor (Vault-backed) for shared-state deployments.")]
    private static partial void LogEphemeralKeyGenerated(ILogger logger, int keyBits);
}
