using System.Globalization;
using System.Security.Cryptography;
using System.Text;
using Microsoft.Extensions.Logging;

namespace Granit.Privacy.DataExport.Security;

/// <summary>
/// In-memory <see cref="IExportHmacSigner"/> using a single key generated at construction
/// time. Suitable for development, tests, and single-instance deployments where export
/// integrity tags do not need to survive a process restart. Production deployments MUST
/// override this with a Vault-backed implementation (planned for a follow-up story).
/// </summary>
/// <remarks>
/// <para>
/// The key is generated by <see cref="RandomNumberGenerator.GetBytes(int)"/> at first use
/// (256 bits). Tags are versioned <c>v1:...</c> so a future Vault-backed signer can accept
/// legacy tags during a rotation window.
/// </para>
/// </remarks>
public sealed partial class EphemeralExportHmacSigner : IExportHmacSigner, IExportContentSigner, IDisposable
{
    private const string Version = "v1";
    private const int KeySizeBytes = 32;

    private readonly byte[] _key;
    private readonly ILogger<EphemeralExportHmacSigner> _logger;
    private bool _disposed;

    /// <summary>Creates a signer with a fresh random key.</summary>
    public EphemeralExportHmacSigner(ILogger<EphemeralExportHmacSigner> logger)
    {
        ArgumentNullException.ThrowIfNull(logger);
        _logger = logger;
        _key = RandomNumberGenerator.GetBytes(KeySizeBytes);
        LogEphemeralKeyGenerated(_logger, KeySizeBytes * 8);
    }

    /// <inheritdoc />
    public string Sign(in ExportHmacParameters parameters)
    {
        ObjectDisposedException.ThrowIf(_disposed, this);

        byte[] canonical = Canonicalize(parameters);
        byte[] mac = HMACSHA256.HashData(_key, canonical);
        return $"{Version}:{Base64UrlEncode(mac)}";
    }

    /// <inheritdoc />
    public bool Verify(in ExportHmacParameters parameters, string tag)
    {
        ObjectDisposedException.ThrowIf(_disposed, this);
        ArgumentException.ThrowIfNullOrEmpty(tag);

        if (parameters.ExpiresAt <= TimeProvider.System.GetUtcNow())
        {
            return false;
        }

        int colonIndex = tag.IndexOf(':', StringComparison.Ordinal);
        if (colonIndex <= 0)
        {
            return false;
        }

        // Only the single key version is known to the ephemeral signer.
        if (!tag.AsSpan(0, colonIndex).SequenceEqual(Version))
        {
            return false;
        }

        string presented = tag[(colonIndex + 1)..];
        byte[] canonical = Canonicalize(parameters);
        byte[] expected = HMACSHA256.HashData(_key, canonical);
        byte[] decoded;
        try
        {
            decoded = Base64UrlDecode(presented);
        }
        catch (FormatException)
        {
            return false;
        }

        return CryptographicOperations.FixedTimeEquals(expected, decoded);
    }

    /// <inheritdoc />
    public string SignBytes(ReadOnlySpan<byte> payload)
    {
        ObjectDisposedException.ThrowIf(_disposed, this);
        byte[] mac = HMACSHA256.HashData(_key, payload);
        return $"{Version}:{Base64UrlEncode(mac)}";
    }

    /// <inheritdoc />
    public bool VerifyBytes(ReadOnlySpan<byte> payload, string tag)
    {
        ObjectDisposedException.ThrowIf(_disposed, this);
        ArgumentException.ThrowIfNullOrEmpty(tag);

        int colonIndex = tag.IndexOf(':', StringComparison.Ordinal);
        if (colonIndex <= 0)
        {
            return false;
        }

        if (!tag.AsSpan(0, colonIndex).SequenceEqual(Version))
        {
            return false;
        }

        string presented = tag[(colonIndex + 1)..];
        byte[] expected = HMACSHA256.HashData(_key, payload);
        byte[] decoded;
        try
        {
            decoded = Base64UrlDecode(presented);
        }
        catch (FormatException)
        {
            return false;
        }

        return CryptographicOperations.FixedTimeEquals(expected, decoded);
    }

    /// <inheritdoc />
    public void Dispose()
    {
        if (_disposed)
        {
            return;
        }

        CryptographicOperations.ZeroMemory(_key);
        _disposed = true;
    }

    private static byte[] Canonicalize(in ExportHmacParameters p)
    {
        // Deterministic, length-prefixed concatenation prevents canonicalisation ambiguity
        // (e.g. two distinct inputs hashing to the same bytes via field-boundary collision).
        StringBuilder sb = new(512);
        AppendField(sb, p.RequestId.ToString("N", CultureInfo.InvariantCulture));
        AppendField(sb, p.SubjectUserId.ToString("N", CultureInfo.InvariantCulture));
        AppendField(sb, p.ProviderName);
        AppendField(sb, p.FragmentKind);
        AppendField(sb, p.SourceContainer);
        AppendField(sb, p.SourceBlobId.ToString("N", CultureInfo.InvariantCulture));
        AppendField(sb, p.EntryPath);
        AppendField(sb, p.ExpiresAt.ToUnixTimeMilliseconds().ToString(CultureInfo.InvariantCulture));
        return Encoding.UTF8.GetBytes(sb.ToString());

        static void AppendField(StringBuilder sb, string value)
        {
            sb.Append(value.Length.ToString(CultureInfo.InvariantCulture));
            sb.Append(':');
            sb.Append(value);
            sb.Append('|');
        }
    }

    private static string Base64UrlEncode(ReadOnlySpan<byte> bytes) =>
        Convert.ToBase64String(bytes)
            .TrimEnd('=')
            .Replace('+', '-')
            .Replace('/', '_');

    private static byte[] Base64UrlDecode(string value)
    {
        string padded = value.Replace('-', '+').Replace('_', '/');
        int padding = (4 - (padded.Length % 4)) % 4;
        if (padding > 0)
        {
            padded += new string('=', padding);
        }

        return Convert.FromBase64String(padded);
    }

    [LoggerMessage(Level = LogLevel.Warning,
        Message = "Privacy export HMAC: ephemeral {KeyBits}-bit key generated. " +
                  "Tags will not survive a process restart. " +
                  "Register a production IExportHmacSigner (Vault-backed) for shared-state deployments.")]
    private static partial void LogEphemeralKeyGenerated(ILogger logger, int keyBits);
}
