using Granit.Core.Events;

namespace Granit.OpenIddict.Events;

/// <summary>
/// Integration event published when a password reset is requested (forgot password flow).
/// </summary>
/// <remarks>
/// Consumed by <c>Granit.Notifications</c> (or app-level subscriber) to send
/// the reset email with a link containing the token. The OpenIddict module does
/// not send emails directly — it publishes this event and lets the consumer
/// decide the delivery channel (SMTP, SendGrid, SES, etc.).
/// </remarks>
/// <param name="UserId">The user identifier.</param>
/// <param name="Email">The user's email address.</param>
/// <param name="ResetToken">The password reset token (URL-safe, generated by ASP.NET Core Identity).</param>
/// <param name="TenantId">The tenant identifier, or <see langword="null"/> for global users.</param>
#pragma warning disable GRSEC003 // ResetToken is a transient token parameter, not a stored secret
public sealed record PasswordResetRequestedEto(
    Guid UserId,
    string Email,
    string ResetToken,
    Guid? TenantId) : IIntegrationEvent;
#pragma warning restore GRSEC003
