using Granit.DataProtection;
using Granit.Encryption;
using Granit.Events;

namespace Granit.Identity.Local.Events;

/// <summary>
/// Integration event published when a user account is locked after exceeding the
/// maximum number of failed login attempts.
/// </summary>
/// <remarks>
/// <para>
/// Consumed by <c>Granit.Identity.Local.Notifications</c> to send a lockout alert
/// containing a password reset link and lockout expiry, so the user can immediately
/// regain access without waiting for the lockout to expire or contacting support.
/// </para>
/// <para>
/// <b>Security note:</b> The <see cref="ResetToken"/> is transient (short-lived, generated by
/// ASP.NET Core Identity with built-in expiry). It is marked <see cref="SensitiveDataAttribute"/>
/// with <see cref="Sensitivity.Restricted"/> so it is redacted in audit logs, MCP output,
/// and diagnostics.
/// </para>
/// </remarks>
/// <param name="UserId">The user identifier.</param>
/// <param name="Email">The user's email address.</param>
/// <param name="FailedAttempts">Number of consecutive failed login attempts that triggered the lockout.</param>
/// <param name="ResetToken">The password reset token (URL-safe, generated by ASP.NET Core Identity).</param>
/// <param name="LockoutEndUtc">The UTC timestamp when the lockout expires (for display in notifications).</param>
/// <param name="TenantId">The tenant identifier, or <see langword="null"/> for global users.</param>
#pragma warning disable GRSEC003 // ResetToken is a transient token parameter, not a stored secret
public sealed record AccountLockedEto(
    Guid UserId,
    [property: SensitiveData(Level = Sensitivity.Restricted, Mode = SensitiveDataMode.Omit), Encrypted]
    string Email,
    int FailedAttempts,
    [property: SensitiveData(Level = Sensitivity.Restricted, Mode = SensitiveDataMode.Omit), Encrypted]
    string ResetToken,
    DateTimeOffset LockoutEndUtc,
    Guid? TenantId) : IIntegrationEvent;
#pragma warning restore GRSEC003
