using Granit.DataProtection;
using Granit.Events;

namespace Granit.Identity.Local.Events;

/// <summary>
/// Integration event published when an email confirmation is requested
/// (registration or resend confirmation flow).
/// </summary>
/// <remarks>
/// The <see cref="Token"/> is transient (short-lived, generated by ASP.NET Core Identity).
/// It is marked with <see cref="SensitiveDataAttribute"/> so it is redacted in logs.
/// </remarks>
/// <param name="UserId">The user identifier.</param>
/// <param name="Token">The email confirmation token (URL-safe).</param>
/// <param name="TenantId">The tenant identifier, or <see langword="null"/> for global users.</param>
#pragma warning disable GRSEC003 // Token is a transient token parameter, not a stored secret
public sealed record EmailConfirmationRequestedEto(
    Guid UserId,
    [property: SensitiveData(Level = Sensitivity.Restricted, Mode = SensitiveDataMode.Omit)]
    string Token,
    Guid? TenantId) : IIntegrationEvent;
#pragma warning restore GRSEC003
