using Granit.DataProtection;
using Granit.Encryption;
using Granit.Events;

namespace Granit.Identity.Local.Events;

/// <summary>
/// Integration event published when a user requests to change their email address.
/// </summary>
/// <remarks>
/// <para>
/// Triggers two notifications:
/// <list type="bullet">
///   <item><c>Security.EmailChangeAlert</c> → sent to the <b>current</b> email (security alert)</item>
///   <item><c>Security.EmailChangeConfirmation</c> → sent to the <b>new</b> email (confirmation link)</item>
/// </list>
/// </para>
/// <para>
/// The token is generated by <c>UserManager.GenerateChangeEmailTokenAsync</c> and encodes
/// the new email address. No additional DB column is needed — ASP.NET Core Identity stores
/// the token in the <c>user_tokens</c> table.
/// </para>
/// </remarks>
/// <param name="UserId">The user identifier.</param>
/// <param name="CurrentEmail">The user's current email address (for the security alert).</param>
/// <param name="NewEmail">The requested new email address (for the confirmation link).</param>
/// <param name="Token">The email change token (URL-safe, encodes the new email).</param>
/// <param name="TenantId">The tenant identifier, or <see langword="null"/> for global users.</param>
#pragma warning disable GRSEC003 // Token is a transient token parameter, not a stored secret
public sealed record EmailChangeRequestedEto(
    Guid UserId,
    [property: SensitiveData(Level = Sensitivity.Restricted, Mode = SensitiveDataMode.Omit), Encrypted]
    string CurrentEmail,
    [property: SensitiveData(Level = Sensitivity.Restricted, Mode = SensitiveDataMode.Omit), Encrypted]
    string NewEmail,
    [property: SensitiveData(Level = Sensitivity.Restricted, Mode = SensitiveDataMode.Omit), Encrypted]
    string Token,
    Guid? TenantId) : IIntegrationEvent;
#pragma warning restore GRSEC003
