using Granit.DataProtection;
using Granit.Events;

namespace Granit.Identity.Local.Events;

/// <summary>
/// Integration event published when a password reset is requested (forgot password flow).
/// </summary>
/// <remarks>
/// <para>
/// Consumed by <c>Granit.Notifications</c> (or app-level subscriber) to send
/// the reset email with a link containing the token. The identity module does
/// not send emails directly — it publishes this event and lets the consumer
/// decide the delivery channel (SMTP, SendGrid, SES, etc.).
/// </para>
/// <para>
/// <b>Security note:</b> The <see cref="ResetToken"/> is transient (short-lived, generated by
/// ASP.NET Core Identity with built-in expiry). It is marked <see cref="SensitiveDataAttribute"/>
/// with <see cref="Sensitivity.Restricted"/> so it is redacted in audit logs, MCP output,
/// and diagnostics. The Wolverine outbox should be pruned frequently to minimize exposure
/// of the plaintext token in the database.
/// </para>
/// </remarks>
/// <param name="UserId">The user identifier.</param>
/// <param name="Email">The user's email address.</param>
/// <param name="ResetToken">The password reset token (URL-safe, generated by ASP.NET Core Identity).</param>
/// <param name="TenantId">The tenant identifier, or <see langword="null"/> for global users.</param>
#pragma warning disable GRSEC003 // ResetToken is a transient token parameter, not a stored secret
public sealed record PasswordResetRequestedEto(
    Guid UserId,
    [property: SensitiveData(Level = Sensitivity.Restricted, Mode = SensitiveDataMode.Omit)]
    string Email,
    [property: SensitiveData(Level = Sensitivity.Restricted, Mode = SensitiveDataMode.Omit)]
    string ResetToken,
    Guid? TenantId) : IIntegrationEvent;
#pragma warning restore GRSEC003
