using Granit.DataProtection;
using Granit.Encryption;
using Granit.Events;

namespace Granit.Identity.Local.Events;

/// <summary>
/// Integration event published when a one-time email code must be delivered for the email
/// two-factor method — during enrollment verification or a login challenge.
/// </summary>
/// <remarks>
/// <para>
/// Consumed by <c>Granit.Notifications</c> (or an app-level subscriber) to deliver the code.
/// The identity module never sends email directly.
/// </para>
/// <para>
/// <b>Security note:</b> <see cref="Code"/> is a short-lived one-time code generated by
/// ASP.NET Core Identity's email token provider. It is marked <see cref="SensitiveDataAttribute"/>
/// with <see cref="Sensitivity.Restricted"/> so it is redacted in audit logs, MCP output, and
/// diagnostics, and <see cref="EncryptedAttribute"/> so it is encrypted at rest in the Wolverine
/// outbox. Prune the outbox frequently to minimize exposure.
/// </para>
/// </remarks>
/// <param name="UserId">The user identifier.</param>
/// <param name="Code">The one-time verification code.</param>
/// <param name="TenantId">The tenant identifier, or <see langword="null"/> for global users.</param>
#pragma warning disable GRSEC003 // Code is a transient OTP parameter, not a stored secret
public sealed record TwoFactorEmailOtpRequestedEto(
    Guid UserId,
    [property: SensitiveData(Level = Sensitivity.Restricted, Mode = SensitiveDataMode.Omit), Encrypted]
    string Code,
    Guid? TenantId) : IIntegrationEvent;
#pragma warning restore GRSEC003
