namespace Granit.Identity.Local.Services;

/// <summary>
/// Manages the email one-time-password second factor: sending codes, opt-in enrollment,
/// and removal.
/// </summary>
/// <remarks>
/// <para>
/// The verification code is generated by ASP.NET Core Identity's email token provider and
/// delivered out-of-band via <c>Granit.Notifications</c>: the service publishes an
/// integration event and never returns the code to the caller.
/// </para>
/// <para>
/// Enrollment is opt-in and tracked independently of the authenticator factor. The login
/// flow MUST gate the email method on <see cref="IsEnabledAsync"/> — the underlying email
/// token provider validates a code for any user with a confirmed email, so without the
/// enrollment check email access alone would bypass a configured authenticator.
/// </para>
/// </remarks>
public interface IEmailTwoFactorService
{
    /// <summary>
    /// Generates a one-time code and publishes the delivery event. No-ops when the user
    /// has no email address. Does not require prior enrollment (used during enrollment too).
    /// </summary>
    Task SendCodeAsync(string userId, CancellationToken cancellationToken = default);

    /// <summary>
    /// Verifies the code and enrolls the email factor, turning on the master switch when it
    /// is the first factor. Throws <see cref="InvalidOperationException"/> on an invalid code.
    /// </summary>
    Task EnableAsync(string userId, string code, CancellationToken cancellationToken = default);

    /// <summary>
    /// Removes the email factor. Clears the master switch and rotates the security stamp
    /// only when no other factor remains.
    /// </summary>
    Task DisableAsync(string userId, CancellationToken cancellationToken = default);

    /// <summary>Whether the user has enrolled the email factor.</summary>
    Task<bool> IsEnabledAsync(string userId, CancellationToken cancellationToken = default);
}
